/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.gamezone.ui;

/**
 *
 * @author USUARIO
 */
public class AccessoryDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AccessoryDialog.class.getName());

    private com.gamezone.service.AccessoryService accessoryService;
    private AccessoryPanel accessoryPanel;

    /**
     * Creates new form AccessoryDialog
     */
    public AccessoryDialog(java.awt.Frame parent, boolean modal) {
        this(parent, modal, null, null);
    }

    public AccessoryDialog(java.awt.Frame parent, boolean modal, com.gamezone.service.AccessoryService accessoryService, AccessoryPanel accessoryPanel) {
        super(parent, modal);
        this.accessoryService = accessoryService;
        this.accessoryPanel = accessoryPanel;
        initComponents();
        setLocationRelativeTo(null);
        btnSave.addActionListener(this::btnSaveActionPerformed);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        lblHeaderTitle = new javax.swing.JLabel();
        lblHeaderSubtitle = new javax.swing.JLabel();
        lblAccessoryType = new javax.swing.JLabel();
        cmbAccessoryType = new javax.swing.JComboBox<>();
        lblTitle = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        lblStock = new javax.swing.JLabel();
        txtId1 = new javax.swing.JTextField();
        lblId2 = new javax.swing.JLabel();
        txtSpecific1 = new javax.swing.JTextField();
        lblPrice1 = new javax.swing.JLabel();
        txtPrice1 = new javax.swing.JTextField();
        lblSpecificSection = new javax.swing.JLabel();
        lblSpecific1 = new javax.swing.JLabel();
        txtTitle2 = new javax.swing.JTextField();
        lblSpecific2 = new javax.swing.JLabel();
        txtSpecific2 = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GameZone - Registrar Accesorio");
        setBackground(new java.awt.Color(255, 255, 255));
        setModal(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHeader.setBackground(new java.awt.Color(20, 40, 75));
        pnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeaderTitle.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblHeaderTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblHeaderTitle.setText("Registrar Nuevo Accesorio");
        pnlHeader.add(lblHeaderTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 15, 320, 25));

        lblHeaderSubtitle.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblHeaderSubtitle.setForeground(new java.awt.Color(210, 220, 235));
        lblHeaderSubtitle.setText("Completa las especificaciones del accesorio");
        pnlHeader.add(lblHeaderSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 360, 20));

        getContentPane().add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 75));

        lblAccessoryType.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblAccessoryType.setForeground(new java.awt.Color(31, 41, 55));
        lblAccessoryType.setText("Tipo de accesorio:*");
        getContentPane().add(lblAccessoryType, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 200, 20));

        cmbAccessoryType.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbAccessoryType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Control", "Cable", "Memoria" }));
        cmbAccessoryType.addActionListener(this::cmbAccessoryTypeActionPerformed);
        getContentPane().add(cmbAccessoryType, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 115, 440, 35));

        lblTitle.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblTitle.setText("Título / Modelo:*");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 205, 20));

        txtStock.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 255, 205, 35));

        lblStock.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblStock.setText("Stock inicial:*");
        getContentPane().add(lblStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 230, 205, 20));

        txtId1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(txtId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 185, 205, 35));

        lblId2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblId2.setText("ID Accesorio:*");
        getContentPane().add(lblId2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 205, 20));

        txtSpecific1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(txtSpecific1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 355, 440, 35));

        lblPrice1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblPrice1.setText("Precio ($):*");
        getContentPane().add(lblPrice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 160, 205, 20));

        txtPrice1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(txtPrice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 185, 205, 35));

        lblSpecificSection.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblSpecificSection.setForeground(new java.awt.Color(30, 136, 229));
        lblSpecificSection.setText("Características específicas:");
        getContentPane().add(lblSpecificSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 305, 440, 20));

        lblSpecific1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblSpecific1.setText("Tipo de conexión (Inalámbrico / Alámbrico):*");
        getContentPane().add(lblSpecific1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 440, 20));

        txtTitle2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(txtTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 205, 35));

        lblSpecific2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblSpecific2.setText("Consolas compatibles (separadas por coma):*");
        getContentPane().add(lblSpecific2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 440, 20));

        txtSpecific2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(txtSpecific2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 425, 440, 35));

        btnCancel.setBackground(new java.awt.Color(229, 57, 53));
        btnCancel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancelar");
        btnCancel.setBorderPainted(false);
        btnCancel.setFocusPainted(false);
        btnCancel.addActionListener(this::btnCancelActionPerformed);
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, 130, 40));

        btnSave.setBackground(new java.awt.Color(46, 125, 50));
        btnSave.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Guardar");
        btnSave.setBorderPainted(false);
        btnSave.setFocusPainted(false);
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, 130, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
       dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void cmbAccessoryTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAccessoryTypeActionPerformed
        String selected = cmbAccessoryType.getSelectedItem().toString().
                trim();

        if ("Cable".equalsIgnoreCase(selected)) {
            lblSpecific1.setText("Longitud en metros:*");
            lblSpecific2.setText("Tipo de conector (HDMI, USB, óptico):*");
        } else if ("Memoria".equalsIgnoreCase(selected)) {
            lblSpecific1.setText("Capacidad de almacenamiento (GB):*");
            lblSpecific2.setText("Tipo de memoria (SD, microSD, interna):*");
        } else { // Control
            lblSpecific1.setText("Tipo de conexión (Inalámbrico / Alámbrico):*");
            lblSpecific2.setText("Consolas compatibles (separadas por coma):*");
        }
    }//GEN-LAST:event_cmbAccessoryTypeActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {
        if (accessoryService == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Servicio de accesorios no disponible.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        String id = txtId1.getText().trim();
        String title = txtTitle2.getText().trim();
        String priceStr = txtPrice1.getText().trim();
        String stockStr = txtStock.getText().trim();
        String spec1 = txtSpecific1.getText().trim();
        String spec2 = txtSpecific2.getText().trim();
        String type = cmbAccessoryType.getSelectedItem().toString().trim();

        if (id.isEmpty() || title.isEmpty() || priceStr.isEmpty() || stockStr.isEmpty() || spec1.isEmpty() || spec2.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor complete todos los campos obligatorios (*).", "Campos incompletos", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (accessoryService.findById(id) != null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ya existe un accesorio con el ID: " + id, "ID duplicado", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        double price;
        try {
            price = Double.parseDouble(priceStr);
            if (price <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "El precio debe ser un número mayor a cero.", "Error de validación", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "El precio debe ser un número válido.", "Error de validación", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int stock;
        try {
            stock = Integer.parseInt(stockStr);
            if (stock < 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "El stock no puede ser un número negativo.", "Error de validación", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "El stock debe ser un número entero válido.", "Error de validación", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            if ("Cable".equalsIgnoreCase(type)) {
                double length;
                try {
                    length = Double.parseDouble(spec1);
                    if (length <= 0) {
                        javax.swing.JOptionPane.showMessageDialog(this, "La longitud del cable debe ser mayor a 0 metros.", "Error de validación", javax.swing.JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                } catch (NumberFormatException e) {
                    javax.swing.JOptionPane.showMessageDialog(this, "La longitud debe ser un número válido en metros.", "Error de validación", javax.swing.JOptionPane.WARNING_MESSAGE);
                    return;
                }
                accessoryService.registerCable(length, spec2, new java.util.ArrayList<>(), id, title, price, stock);
            } else if ("Memoria".equalsIgnoreCase(type)) {
                int capacity;
                try {
                    capacity = Integer.parseInt(spec1);
                    if (capacity <= 0) {
                        javax.swing.JOptionPane.showMessageDialog(this, "La capacidad debe ser un número entero mayor a 0 GB.", "Error de validación", javax.swing.JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                } catch (NumberFormatException e) {
                    javax.swing.JOptionPane.showMessageDialog(this, "La capacidad debe ser un número entero válido.", "Error de validación", javax.swing.JOptionPane.WARNING_MESSAGE);
                    return;
                }
                accessoryService.registerMemory(capacity, spec2, new java.util.ArrayList<>(), id, title, price, stock);
            } else { // Control
                java.util.List<String> consoles = java.util.Arrays.stream(spec2.split(","))
                        .map(String::trim)
                        .filter(s -> !s.isEmpty())
                        .collect(java.util.stream.Collectors.toList());
                accessoryService.registerController(spec1, consoles, id, title, price, stock);
            }

            javax.swing.JOptionPane.showMessageDialog(this, "Accesorio registrado exitosamente.", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            if (accessoryPanel != null) {
                accessoryPanel.loadAccessories();
            }
            dispose();
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al registrar el accesorio: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                AccessoryDialog dialog = new AccessoryDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbAccessoryType;
    private javax.swing.JLabel lblAccessoryType;
    private javax.swing.JLabel lblHeaderSubtitle;
    private javax.swing.JLabel lblHeaderTitle;
    private javax.swing.JLabel lblId2;
    private javax.swing.JLabel lblPrice1;
    private javax.swing.JLabel lblSpecific1;
    private javax.swing.JLabel lblSpecific2;
    private javax.swing.JLabel lblSpecificSection;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JTextField txtId1;
    private javax.swing.JTextField txtPrice1;
    private javax.swing.JTextField txtSpecific1;
    private javax.swing.JTextField txtSpecific2;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtTitle2;
    // End of variables declaration//GEN-END:variables
}
