/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.gamezone.ui;

/**
 *
 * @author USUARIO
 */
public class AccessoryPanel extends javax.swing.JPanel {

    /**
     * Creates new form AccessoryPanel
     */
    public AccessoryPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloAccesorios = new javax.swing.JLabel();
        lblSubtituloAccesorios = new javax.swing.JLabel();
        btnNuevoAccesorio = new javax.swing.JButton();
        pnlContenidoAccesorios = new javax.swing.JPanel();
        lblBuscarAccesorio = new javax.swing.JLabel();
        txtBuscarAccesorio = new javax.swing.JTextField();
        btnBuscarAccesorio = new javax.swing.JButton();
        lblFiltrarTipo = new javax.swing.JLabel();
        cmbFiltrarTipo = new javax.swing.JComboBox<>();
        btnCompatibilidad = new javax.swing.JButton();
        JsCompatible = new javax.swing.JScrollPane();
        tblAccesorios = new javax.swing.JTable();

        setBackground(new java.awt.Color(245, 247, 250));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloAccesorios.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        lblTituloAccesorios.setForeground(new java.awt.Color(31, 41, 55));
        lblTituloAccesorios.setText("Accesorios");
        add(lblTituloAccesorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 35, 200, 35));

        lblSubtituloAccesorios.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSubtituloAccesorios.setForeground(new java.awt.Color(107, 114, 128));
        lblSubtituloAccesorios.setText("Gestión de controles, cables, memorias y compatibilidad");
        add(lblSubtituloAccesorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 75, 450, 25));

        btnNuevoAccesorio.setBackground(new java.awt.Color(30, 136, 229));
        btnNuevoAccesorio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnNuevoAccesorio.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoAccesorio.setText("+ Nuevo accesorio");
        btnNuevoAccesorio.setBorderPainted(false);
        btnNuevoAccesorio.setFocusPainted(false);
        btnNuevoAccesorio.addActionListener(this::btnNuevoAccesorioActionPerformed);
        add(btnNuevoAccesorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 30, 175, 40));

        pnlContenidoAccesorios.setBackground(new java.awt.Color(255, 255, 255));
        pnlContenidoAccesorios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBuscarAccesorio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblBuscarAccesorio.setForeground(new java.awt.Color(31, 41, 55));
        lblBuscarAccesorio.setText("Buscar");
        pnlContenidoAccesorios.add(lblBuscarAccesorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 25, 60, 25));

        txtBuscarAccesorio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtBuscarAccesorio.addActionListener(this::txtBuscarAccesorioActionPerformed);
        pnlContenidoAccesorios.add(txtBuscarAccesorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 20, 250, 35));

        btnBuscarAccesorio.setBackground(new java.awt.Color(30, 136, 229));
        btnBuscarAccesorio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnBuscarAccesorio.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarAccesorio.setText("Buscar");
        btnBuscarAccesorio.setBorderPainted(false);
        btnBuscarAccesorio.setFocusPainted(false);
        pnlContenidoAccesorios.add(btnBuscarAccesorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 20, 95, 35));

        lblFiltrarTipo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblFiltrarTipo.setForeground(new java.awt.Color(31, 41, 55));
        lblFiltrarTipo.setText("Tipo:");
        pnlContenidoAccesorios.add(lblFiltrarTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 25, 45, 25));

        cmbFiltrarTipo.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        cmbFiltrarTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos los tipos", "Controles", "Cables", "Memorias" }));
        pnlContenidoAccesorios.add(cmbFiltrarTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 160, 35));

        btnCompatibilidad.setBackground(new java.awt.Color(38, 198, 218));
        btnCompatibilidad.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCompatibilidad.setForeground(new java.awt.Color(255, 255, 255));
        btnCompatibilidad.setText("Ver compatibilidad");
        btnCompatibilidad.setBorderPainted(false);
        btnCompatibilidad.setFocusPainted(false);
        pnlContenidoAccesorios.add(btnCompatibilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 185, 35));

        tblAccesorios.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        tblAccesorios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Titulo", "Tipo", "Precio", "Stock", "Especificación", "Consolas Compatibles"
            }
        ));
        JsCompatible.setViewportView(tblAccesorios);

        pnlContenidoAccesorios.add(JsCompatible, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 85, 870, 400));

        add(pnlContenidoAccesorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 920, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarAccesorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarAccesorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarAccesorioActionPerformed

    private void btnNuevoAccesorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoAccesorioActionPerformed
        java.awt.Frame parentFrame = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);
        AccessoryDialog dialog = new AccessoryDialog(parentFrame, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnNuevoAccesorioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JsCompatible;
    private javax.swing.JButton btnBuscarAccesorio;
    private javax.swing.JButton btnCompatibilidad;
    private javax.swing.JButton btnNuevoAccesorio;
    private javax.swing.JComboBox<String> cmbFiltrarTipo;
    private javax.swing.JLabel lblBuscarAccesorio;
    private javax.swing.JLabel lblFiltrarTipo;
    private javax.swing.JLabel lblSubtituloAccesorios;
    private javax.swing.JLabel lblTituloAccesorios;
    private javax.swing.JPanel pnlContenidoAccesorios;
    private javax.swing.JTable tblAccesorios;
    private javax.swing.JTextField txtBuscarAccesorio;
    // End of variables declaration//GEN-END:variables
}
