/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.gamezone.ui;

/**
 *
 * @author USUARIO
 */
public class CustomerDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CustomerDialog.class.getName());

    /**
     * Creates new form CustomerDialog
     */
    public CustomerDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnlHeader = new javax.swing.JPanel();
        lblHeaderTitle = new javax.swing.JLabel();
        lblHeaderSubtitle = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtFirstName1 = new javax.swing.JTextField();
        lblLastName1 = new javax.swing.JLabel();
        txtLastName1 = new javax.swing.JTextField();
        lblPhone1 = new javax.swing.JLabel();
        txtPhone1 = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GameZone - Registrar Cliente");
        setBackground(new java.awt.Color(255, 255, 255));
        setModal(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHeader.setBackground(new java.awt.Color(20, 40, 75));
        pnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeaderTitle.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblHeaderTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblHeaderTitle.setText("Registrar Nuevo Cliente");
        pnlHeader.add(lblHeaderTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 15, 300, 25));

        lblHeaderSubtitle.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblHeaderSubtitle.setForeground(new java.awt.Color(210, 220, 235));
        lblHeaderSubtitle.setText("Completa la información del cliente");
        pnlHeader.add(lblHeaderSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 300, 20));

        getContentPane().add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 75));

        lblId.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblId.setForeground(new java.awt.Color(31, 41, 55));
        lblId.setText("Identificación / ID:*");
        getContentPane().add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 95, 200, 20));

        txtId.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtId.setForeground(new java.awt.Color(31, 41, 55));
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 410, 35));

        lblFirstName.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(31, 41, 55));
        lblFirstName.setText("Nombre:*");
        getContentPane().add(lblFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 165, 200, 20));

        txtEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(31, 41, 55));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 410, 35));

        lblEmail.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(31, 41, 55));
        lblEmail.setText("Correo Electrónico:*");
        getContentPane().add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 200, 20));

        txtFirstName1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtFirstName1.setForeground(new java.awt.Color(31, 41, 55));
        getContentPane().add(txtFirstName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 410, 35));

        lblLastName1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblLastName1.setForeground(new java.awt.Color(31, 41, 55));
        lblLastName1.setText("Apellido:*");
        getContentPane().add(lblLastName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 235, 200, 20));

        txtLastName1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtLastName1.setForeground(new java.awt.Color(31, 41, 55));
        getContentPane().add(txtLastName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 410, 35));

        lblPhone1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblPhone1.setForeground(new java.awt.Color(31, 41, 55));
        lblPhone1.setText("Teléfono:*");
        getContentPane().add(lblPhone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 305, 200, 20));

        txtPhone1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPhone1.setForeground(new java.awt.Color(31, 41, 55));
        getContentPane().add(txtPhone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 410, 35));

        btnCancel.setBackground(new java.awt.Color(229, 57, 53));
        btnCancel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancelar");
        btnCancel.setBorderPainted(false);
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.setFocusPainted(false);
        btnCancel.addActionListener(this::btnCancelActionPerformed);
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 120, 40));

        btnSave.setBackground(new java.awt.Color(46, 125, 50));
        btnSave.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Guardar Cliente");
        btnSave.setBorderPainted(false);
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.setFocusPainted(false);
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, 140, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose(); // Cierra la ventanita emergente
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                CustomerDialog dialog = new CustomerDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblHeaderSubtitle;
    private javax.swing.JLabel lblHeaderTitle;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblLastName1;
    private javax.swing.JLabel lblPhone1;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName1;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLastName1;
    private javax.swing.JTextField txtPhone1;
    // End of variables declaration//GEN-END:variables
}
