/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.gamezone.ui;

import com.gamezone.model.Customer;
import com.gamezone.service.PersonService;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class CustomerPanel extends javax.swing.JPanel {

    private PersonService personService;
    /**
     * Creates new form CustomerPanel
     */
    public CustomerPanel() {
        initComponents();
    }

    public CustomerPanel(PersonService personService) {                
            this.personService = personService;
            initComponents();
            loadCustomers(); // Carga la lista inicial
        } 
    
    public void loadCustomers() {
        if (personService == null) {
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblClientes.
                getModel();
        model.setRowCount(0);

        for (Customer c : personService.listAllCustomers()) {
            model.addRow(new Object[]{
                c.getId(),
                c.getFirstName(),
                c.getLastName(),
                c.getPhone(),
                c.getEmail()
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloClientes = new javax.swing.JLabel();
        lblSubtituloClientes = new javax.swing.JLabel();
        btnNuevoCliente = new javax.swing.JButton();
        pnlContenidoClientes = new javax.swing.JPanel();
        lblBuscarCliente = new javax.swing.JLabel();
        txtBuscarCliente = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();
        JstableCliente = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();

        setBackground(new java.awt.Color(245, 247, 250));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloClientes.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        lblTituloClientes.setForeground(new java.awt.Color(31, 41, 55));
        lblTituloClientes.setText("Clientes");
        add(lblTituloClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 35, 180, 35));

        lblSubtituloClientes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSubtituloClientes.setForeground(new java.awt.Color(107, 114, 128));
        lblSubtituloClientes.setText("Gestiona los clientes registrados en GameZone.");
        add(lblSubtituloClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 75, 350, 25));

        btnNuevoCliente.setBackground(new java.awt.Color(30, 136, 229));
        btnNuevoCliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnNuevoCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoCliente.setText("+ Nuevo cliente");
        btnNuevoCliente.setBorderPainted(false);
        btnNuevoCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevoCliente.setFocusPainted(false);
        btnNuevoCliente.addActionListener(this::btnNuevoClienteActionPerformed);
        add(btnNuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, 165, 40));

        pnlContenidoClientes.setBackground(new java.awt.Color(255, 255, 255));
        pnlContenidoClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBuscarCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblBuscarCliente.setForeground(new java.awt.Color(31, 41, 55));
        lblBuscarCliente.setText("Buscar cliente");
        pnlContenidoClientes.add(lblBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 25, 130, 25));

        txtBuscarCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtBuscarCliente.setForeground(new java.awt.Color(31, 41, 55));
        pnlContenidoClientes.add(txtBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 20, 300, 35));

        btnBuscarCliente.setBackground(new java.awt.Color(30, 136, 229));
        btnBuscarCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnBuscarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.setBorderPainted(false);
        btnBuscarCliente.setFocusPainted(false);
        btnBuscarCliente.addActionListener(this::btnBuscarClienteActionPerformed);
        pnlContenidoClientes.add(btnBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 110, 35));

        tblClientes.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        tblClientes.setForeground(new java.awt.Color(31, 41, 55));
        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido", "Telefono", "Email"
            }
        ));
        JstableCliente.setViewportView(tblClientes);

        pnlContenidoClientes.add(JstableCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 85, 870, -1));

        add(pnlContenidoClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 920, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoClienteActionPerformed
        java.awt.Frame parentFrame = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);
        CustomerDialog dialog = new CustomerDialog(parentFrame, true,
                personService, this);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnNuevoClienteActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        if (personService == null)
            return;
        String query = txtBuscarCliente.getText().trim().toLowerCase();

        if (query.isEmpty()) {
            loadCustomers();
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblClientes.
                getModel();
        model.setRowCount(0);

        for (Customer c : personService.listAllCustomers()) {
            if (c.getId().toLowerCase().contains(query)
                    || c.getFirstName().toLowerCase().contains(query)
                    || c.getLastName().toLowerCase().contains(query)
                    || c.getEmail().toLowerCase().contains(query)) {
                model.addRow(new Object[]{
                    c.getId(), c.getFirstName(), c.getLastName(), c.
                    getPhone(), c.getEmail()
                });
            }
        }
    }//GEN-LAST:event_btnBuscarClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JstableCliente;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnNuevoCliente;
    private javax.swing.JLabel lblBuscarCliente;
    private javax.swing.JLabel lblSubtituloClientes;
    private javax.swing.JLabel lblTituloClientes;
    private javax.swing.JPanel pnlContenidoClientes;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtBuscarCliente;
    // End of variables declaration//GEN-END:variables
}
