
package com.gamezone.ui;


public class MainFrame extends javax.swing.JFrame {
   
    private ProductPanel productPanel;
    private CustomerPanel customerPanel;
    private SellerPanel sellerPanel;
    private SalePanel salePanel;
    private PromotionPanel promotionPanel;
    private AccessoryPanel accessoryPanel;
    private WarrantyPanel warrantyPanel;
    private ReturnPanel returnPanel;
    private ReportsPanel reportsPanel;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.setLocationRelativeTo(null); // Opcional: centra la ventana en pantalla    
        this.productPanel = new ProductPanel(); 
        this.customerPanel = new CustomerPanel();
        this.sellerPanel = new SellerPanel();
        this.salePanel = new SalePanel();
        this.promotionPanel = new PromotionPanel();
        this.accessoryPanel = new AccessoryPanel();
        this.warrantyPanel = new WarrantyPanel();
        this.returnPanel = new ReturnPanel();
        this.reportsPanel = new ReportsPanel();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelMenuLateral = new javax.swing.JPanel();
        etiquetaIconoLogo = new javax.swing.JLabel();
        etiquetaSubtitulo = new javax.swing.JLabel();
        etiquetaMarca = new javax.swing.JLabel();
        botonInicio = new javax.swing.JButton();
        botonReportes = new javax.swing.JButton();
        botonProductos1 = new javax.swing.JButton();
        botonClientes1 = new javax.swing.JButton();
        botonVendedores1 = new javax.swing.JButton();
        botonVentas1 = new javax.swing.JButton();
        botonPromociones1 = new javax.swing.JButton();
        botonAccesorios1 = new javax.swing.JButton();
        botonGarantias1 = new javax.swing.JButton();
        botonDevoluciones1 = new javax.swing.JButton();
        panelContenido = new javax.swing.JPanel();
        etiquetaTitulo = new javax.swing.JLabel();
        botonNuevaVenta = new javax.swing.JButton();
        tarjetaProductos = new javax.swing.JPanel();
        etiquetaProductos = new javax.swing.JLabel();
        valorProductos = new javax.swing.JLabel();
        tarjetaClientes = new javax.swing.JPanel();
        etiquetaClientes = new javax.swing.JLabel();
        valorClientes = new javax.swing.JLabel();
        tarjetaDevolucionesMes = new javax.swing.JPanel();
        etiquetaDevolucionesMes = new javax.swing.JLabel();
        valorDevolucionesMes = new javax.swing.JLabel();
        tarjetaPromocionesActivas = new javax.swing.JPanel();
        etiquetaPromocionesActivas = new javax.swing.JLabel();
        valorPromocionesActivas = new javax.swing.JLabel();
        panelVentasRecientes = new javax.swing.JPanel();
        etiquetaVentasRecientes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVentasRecientes = new javax.swing.JTable();
        panelAccionesRapidas = new javax.swing.JPanel();
        AccionesRpidas = new javax.swing.JLabel();
        botonRegistrarProducto = new javax.swing.JButton();
        botonRegistrarDevolucion = new javax.swing.JButton();
        botonConsultarGarantia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GameZone Unicesar - Management System");
        setResizable(false);

        panelPrincipal.setBackground(new java.awt.Color(248, 249, 252));
        panelPrincipal.setPreferredSize(new java.awt.Dimension(1200, 720));
        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMenuLateral.setBackground(new java.awt.Color(20, 40, 75));
        panelMenuLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaIconoLogo.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaIconoLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaIconoLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo-Gamezone.png"))); // NOI18N
        panelMenuLateral.add(etiquetaIconoLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 85, 50));

        etiquetaSubtitulo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        etiquetaSubtitulo.setForeground(new java.awt.Color(210, 220, 235));
        etiquetaSubtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaSubtitulo.setText("Sistema de gestión");
        panelMenuLateral.add(etiquetaSubtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 124, 200, 22));

        etiquetaMarca.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        etiquetaMarca.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaMarca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaMarca.setText("GAMEZONE");
        panelMenuLateral.add(etiquetaMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 95, 200, 30));

        botonInicio.setBackground(new java.awt.Color(20, 40, 75));
        botonInicio.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        botonInicio.setForeground(new java.awt.Color(255, 255, 255));
        botonInicio.setText("Inicio");
        botonInicio.setBorderPainted(false);
        botonInicio.setFocusPainted(false);
        botonInicio.addActionListener(this::botonInicioActionPerformed);
        panelMenuLateral.add(botonInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 180, 200, 42));

        botonReportes.setBackground(new java.awt.Color(20, 40, 75));
        botonReportes.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        botonReportes.setForeground(new java.awt.Color(255, 255, 255));
        botonReportes.setText("Reportes");
        botonReportes.setBorderPainted(false);
        botonReportes.setFocusPainted(false);
        botonReportes.addActionListener(this::botonReportesActionPerformed);
        panelMenuLateral.add(botonReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 630, 200, 42));

        botonProductos1.setBackground(new java.awt.Color(20, 40, 75));
        botonProductos1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        botonProductos1.setForeground(new java.awt.Color(255, 255, 255));
        botonProductos1.setText("Productos");
        botonProductos1.setBorderPainted(false);
        botonProductos1.setFocusPainted(false);
        botonProductos1.addActionListener(this::botonProductos1ActionPerformed);
        panelMenuLateral.add(botonProductos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 230, 200, 42));

        botonClientes1.setBackground(new java.awt.Color(20, 40, 75));
        botonClientes1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        botonClientes1.setForeground(new java.awt.Color(255, 255, 255));
        botonClientes1.setText("\tClientes");
        botonClientes1.setBorderPainted(false);
        botonClientes1.setFocusPainted(false);
        botonClientes1.addActionListener(this::botonClientes1ActionPerformed);
        panelMenuLateral.add(botonClientes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 280, 200, 42));

        botonVendedores1.setBackground(new java.awt.Color(20, 40, 75));
        botonVendedores1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        botonVendedores1.setForeground(new java.awt.Color(255, 255, 255));
        botonVendedores1.setText("Vendedores");
        botonVendedores1.setBorderPainted(false);
        botonVendedores1.setFocusPainted(false);
        botonVendedores1.addActionListener(this::botonVendedores1ActionPerformed);
        panelMenuLateral.add(botonVendedores1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 330, 200, 42));

        botonVentas1.setBackground(new java.awt.Color(20, 40, 75));
        botonVentas1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        botonVentas1.setForeground(new java.awt.Color(255, 255, 255));
        botonVentas1.setText("Ventas");
        botonVentas1.setBorderPainted(false);
        botonVentas1.setFocusPainted(false);
        botonVentas1.addActionListener(this::botonVentas1ActionPerformed);
        panelMenuLateral.add(botonVentas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 380, 200, 42));

        botonPromociones1.setBackground(new java.awt.Color(20, 40, 75));
        botonPromociones1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        botonPromociones1.setForeground(new java.awt.Color(255, 255, 255));
        botonPromociones1.setText("Promociones");
        botonPromociones1.setBorderPainted(false);
        botonPromociones1.setFocusPainted(false);
        botonPromociones1.addActionListener(this::botonPromociones1ActionPerformed);
        panelMenuLateral.add(botonPromociones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 430, 200, 42));

        botonAccesorios1.setBackground(new java.awt.Color(20, 40, 75));
        botonAccesorios1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        botonAccesorios1.setForeground(new java.awt.Color(255, 255, 255));
        botonAccesorios1.setText("\tAccesorios");
        botonAccesorios1.setBorderPainted(false);
        botonAccesorios1.setFocusPainted(false);
        botonAccesorios1.addActionListener(this::botonAccesorios1ActionPerformed);
        panelMenuLateral.add(botonAccesorios1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 480, 200, 42));

        botonGarantias1.setBackground(new java.awt.Color(20, 40, 75));
        botonGarantias1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        botonGarantias1.setForeground(new java.awt.Color(255, 255, 255));
        botonGarantias1.setText("Garantías");
        botonGarantias1.setBorderPainted(false);
        botonGarantias1.setFocusPainted(false);
        botonGarantias1.addActionListener(this::botonGarantias1ActionPerformed);
        panelMenuLateral.add(botonGarantias1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 530, 200, 42));

        botonDevoluciones1.setBackground(new java.awt.Color(20, 40, 75));
        botonDevoluciones1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        botonDevoluciones1.setForeground(new java.awt.Color(255, 255, 255));
        botonDevoluciones1.setText("Devoluciones");
        botonDevoluciones1.setBorderPainted(false);
        botonDevoluciones1.setFocusPainted(false);
        botonDevoluciones1.addActionListener(this::botonDevoluciones1ActionPerformed);
        panelMenuLateral.add(botonDevoluciones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 580, 200, 42));

        panelPrincipal.add(panelMenuLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 720));

        panelContenido.setBackground(new java.awt.Color(248, 249, 252));
        panelContenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaTitulo.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        etiquetaTitulo.setForeground(new java.awt.Color(25, 25, 25));
        etiquetaTitulo.setText("Panel de control");
        panelContenido.add(etiquetaTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 40, 240, 45));

        botonNuevaVenta.setBackground(new java.awt.Color(30, 136, 229));
        botonNuevaVenta.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        botonNuevaVenta.setForeground(new java.awt.Color(255, 255, 255));
        botonNuevaVenta.setText("Nueva venta");
        botonNuevaVenta.setBorderPainted(false);
        botonNuevaVenta.setFocusPainted(false);
        botonNuevaVenta.addActionListener(this::botonNuevaVentaActionPerformed);
        panelContenido.add(botonNuevaVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 40, 170, 46));

        tarjetaProductos.setBackground(new java.awt.Color(255, 255, 255));
        tarjetaProductos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 198, 218), 3));
        tarjetaProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaProductos.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        etiquetaProductos.setForeground(new java.awt.Color(25, 25, 25));
        etiquetaProductos.setText("Productos");
        tarjetaProductos.add(etiquetaProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 18, 125, 25));

        valorProductos.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        valorProductos.setForeground(new java.awt.Color(25, 25, 25));
        valorProductos.setText("0");
        tarjetaProductos.add(valorProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        panelContenido.add(tarjetaProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 120, 190, 115));

        tarjetaClientes.setBackground(new java.awt.Color(255, 255, 255));
        tarjetaClientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 198, 218), 3));
        tarjetaClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaClientes.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        etiquetaClientes.setForeground(new java.awt.Color(25, 25, 25));
        etiquetaClientes.setText("Clientes");
        tarjetaClientes.add(etiquetaClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 16, 150, 25));

        valorClientes.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        valorClientes.setForeground(new java.awt.Color(25, 25, 25));
        valorClientes.setText("0");
        tarjetaClientes.add(valorClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 52, 100, 40));

        panelContenido.add(tarjetaClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 120, 190, 115));

        tarjetaDevolucionesMes.setBackground(new java.awt.Color(255, 255, 255));
        tarjetaDevolucionesMes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 198, 218), 3));
        tarjetaDevolucionesMes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaDevolucionesMes.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        etiquetaDevolucionesMes.setForeground(new java.awt.Color(25, 25, 25));
        etiquetaDevolucionesMes.setText("Devoluciones del mes");
        tarjetaDevolucionesMes.add(etiquetaDevolucionesMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 16, 165, 25));

        valorDevolucionesMes.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        valorDevolucionesMes.setForeground(new java.awt.Color(25, 25, 25));
        valorDevolucionesMes.setText("0");
        tarjetaDevolucionesMes.add(valorDevolucionesMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 52, 100, 40));

        panelContenido.add(tarjetaDevolucionesMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 120, 190, 115));

        tarjetaPromocionesActivas.setBackground(new java.awt.Color(255, 255, 255));
        tarjetaPromocionesActivas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 198, 218), 3));
        tarjetaPromocionesActivas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaPromocionesActivas.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        etiquetaPromocionesActivas.setForeground(new java.awt.Color(25, 25, 25));
        etiquetaPromocionesActivas.setText("Promociones activas");
        tarjetaPromocionesActivas.add(etiquetaPromocionesActivas, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 16, 165, 25));

        valorPromocionesActivas.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        valorPromocionesActivas.setForeground(new java.awt.Color(25, 25, 25));
        valorPromocionesActivas.setText("0");
        tarjetaPromocionesActivas.add(valorPromocionesActivas, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 52, 100, 40));

        panelContenido.add(tarjetaPromocionesActivas, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 120, 190, 115));

        panelVentasRecientes.setBackground(new java.awt.Color(255, 255, 255));
        panelVentasRecientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(225, 228, 235)));
        panelVentasRecientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaVentasRecientes.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiquetaVentasRecientes.setForeground(new java.awt.Color(25, 25, 25));
        etiquetaVentasRecientes.setText("Ventas recientes");
        panelVentasRecientes.add(etiquetaVentasRecientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, 250, 32));

        tablaVentasRecientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cliente", "Vendedor", "Total", "Fecha"
            }
        ));
        tablaVentasRecientes.setEnabled(false);
        jScrollPane1.setViewportView(tablaVentasRecientes);

        panelVentasRecientes.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 65, 570, 275));

        panelContenido.add(panelVentasRecientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 270, 610, 370));

        panelAccionesRapidas.setBackground(new java.awt.Color(255, 255, 255));
        panelAccionesRapidas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(225, 228, 235)));
        panelAccionesRapidas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AccionesRpidas.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        AccionesRpidas.setForeground(new java.awt.Color(25, 25, 25));
        AccionesRpidas.setText("Acciones rápidas");
        panelAccionesRapidas.add(AccionesRpidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 16, 190, 32));

        botonRegistrarProducto.setBackground(new java.awt.Color(30, 136, 229));
        botonRegistrarProducto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botonRegistrarProducto.setForeground(new java.awt.Color(255, 255, 255));
        botonRegistrarProducto.setText("Registrar producto");
        botonRegistrarProducto.setBorderPainted(false);
        botonRegistrarProducto.setFocusPainted(false);
        botonRegistrarProducto.addActionListener(this::botonRegistrarProductoActionPerformed);
        panelAccionesRapidas.add(botonRegistrarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 75, 184, 48));

        botonRegistrarDevolucion.setBackground(new java.awt.Color(30, 136, 229));
        botonRegistrarDevolucion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botonRegistrarDevolucion.setForeground(new java.awt.Color(255, 255, 255));
        botonRegistrarDevolucion.setText("Registrar devolución");
        botonRegistrarDevolucion.setBorderPainted(false);
        botonRegistrarDevolucion.setFocusPainted(false);
        botonRegistrarDevolucion.addActionListener(this::botonRegistrarDevolucionActionPerformed);
        panelAccionesRapidas.add(botonRegistrarDevolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 145, 184, 48));

        botonConsultarGarantia.setBackground(new java.awt.Color(30, 136, 229));
        botonConsultarGarantia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botonConsultarGarantia.setForeground(new java.awt.Color(255, 255, 255));
        botonConsultarGarantia.setText("Consultar garantía");
        botonConsultarGarantia.setBorderPainted(false);
        botonConsultarGarantia.setFocusPainted(false);
        botonConsultarGarantia.addActionListener(this::botonConsultarGarantiaActionPerformed);
        panelAccionesRapidas.add(botonConsultarGarantia, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 215, 184, 48));

        panelContenido.add(panelAccionesRapidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, 220, 370));

        panelPrincipal.add(panelContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 970, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonProductos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProductos1ActionPerformed
        cambiarPanel(productPanel);
    }//GEN-LAST:event_botonProductos1ActionPerformed

    private void botonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInicioActionPerformed
        mostrarInicio();
    }//GEN-LAST:event_botonInicioActionPerformed

    private void botonRegistrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarProductoActionPerformed
        cambiarPanel(productPanel);
    }//GEN-LAST:event_botonRegistrarProductoActionPerformed

    private void botonClientes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonClientes1ActionPerformed
        cambiarPanel(customerPanel);
    }//GEN-LAST:event_botonClientes1ActionPerformed

    private void botonVendedores1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVendedores1ActionPerformed
        cambiarPanel(sellerPanel);
    }//GEN-LAST:event_botonVendedores1ActionPerformed

    private void botonVentas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVentas1ActionPerformed
        cambiarPanel(salePanel);
    }//GEN-LAST:event_botonVentas1ActionPerformed

    private void botonNuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevaVentaActionPerformed
        SaleDialog dialog = new SaleDialog(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_botonNuevaVentaActionPerformed

    private void botonPromociones1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPromociones1ActionPerformed
        cambiarPanel(promotionPanel);
    }//GEN-LAST:event_botonPromociones1ActionPerformed

    private void botonAccesorios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAccesorios1ActionPerformed
        cambiarPanel(accessoryPanel);
    }//GEN-LAST:event_botonAccesorios1ActionPerformed

    private void botonGarantias1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGarantias1ActionPerformed
        cambiarPanel(warrantyPanel);
    }//GEN-LAST:event_botonGarantias1ActionPerformed

    private void botonConsultarGarantiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarGarantiaActionPerformed
        cambiarPanel(warrantyPanel);
    }//GEN-LAST:event_botonConsultarGarantiaActionPerformed

    private void botonDevoluciones1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDevoluciones1ActionPerformed
        cambiarPanel(returnPanel);
    }//GEN-LAST:event_botonDevoluciones1ActionPerformed

    private void botonRegistrarDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarDevolucionActionPerformed
        cambiarPanel(returnPanel);
    }//GEN-LAST:event_botonRegistrarDevolucionActionPerformed

    private void botonReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReportesActionPerformed
        cambiarPanel(reportsPanel);
    }//GEN-LAST:event_botonReportesActionPerformed

    /**                                                                                 
     * Reemplaza el contenido actual del panelContenido por un nuevo panel.
     */
    private void cambiarPanel(javax.swing.JPanel nuevoPanel) {
        nuevoPanel.setSize(970, 720);
        nuevoPanel.setLocation(0, 0);

        panelContenido.removeAll();
        panelContenido.add(nuevoPanel, new org.netbeans.lib.awtextra.
  AbsoluteConstraints(0, 0, 970, 720));
        panelContenido.revalidate();
        panelContenido.repaint();
    }

    /**
     * Restaura la vista inicial (Dashboard / Panel de control).
     */
    private void mostrarInicio() {
        panelContenido.removeAll();

        // Restaurar los componentes originales del Dashboard con sus posiciones
        panelContenido.add(etiquetaTitulo, new org.netbeans.lib.awtextra.
  AbsoluteConstraints(55, 40, 240, 45));
        panelContenido.add(botonNuevaVenta, new org.netbeans.lib.awtextra.
  AbsoluteConstraints(740, 40, 170, 46));
        panelContenido.add(tarjetaProductos, new org.netbeans.lib.awtextra.
  AbsoluteConstraints(55, 120, 190, 115));
        panelContenido.add(tarjetaClientes, new org.netbeans.lib.awtextra.
  AbsoluteConstraints(265, 120, 190, 115));
        panelContenido.add(tarjetaDevolucionesMes, new org.netbeans.lib.awtextra.
  AbsoluteConstraints(475, 120, 190, 115));
        panelContenido.add(tarjetaPromocionesActivas, new org.netbeans.lib.awtextra.
  AbsoluteConstraints(685, 120, 190, 115));
        panelContenido.add(panelVentasRecientes, new org.netbeans.lib.awtextra.
  AbsoluteConstraints(55, 270, 610, 370));
        panelContenido.add(panelAccionesRapidas, new org.netbeans.lib.awtextra.
  AbsoluteConstraints(690, 270, 220, 370));

        panelContenido.revalidate();
        panelContenido.repaint();
    }   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccionesRpidas;
    private javax.swing.JButton botonAccesorios1;
    private javax.swing.JButton botonClientes1;
    private javax.swing.JButton botonConsultarGarantia;
    private javax.swing.JButton botonDevoluciones1;
    private javax.swing.JButton botonGarantias1;
    private javax.swing.JButton botonInicio;
    private javax.swing.JButton botonNuevaVenta;
    private javax.swing.JButton botonProductos1;
    private javax.swing.JButton botonPromociones1;
    private javax.swing.JButton botonRegistrarDevolucion;
    private javax.swing.JButton botonRegistrarProducto;
    private javax.swing.JButton botonReportes;
    private javax.swing.JButton botonVendedores1;
    private javax.swing.JButton botonVentas1;
    private javax.swing.JLabel etiquetaClientes;
    private javax.swing.JLabel etiquetaDevolucionesMes;
    private javax.swing.JLabel etiquetaIconoLogo;
    private javax.swing.JLabel etiquetaMarca;
    private javax.swing.JLabel etiquetaProductos;
    private javax.swing.JLabel etiquetaPromocionesActivas;
    private javax.swing.JLabel etiquetaSubtitulo;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JLabel etiquetaVentasRecientes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelAccionesRapidas;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JPanel panelMenuLateral;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelVentasRecientes;
    private javax.swing.JTable tablaVentasRecientes;
    private javax.swing.JPanel tarjetaClientes;
    private javax.swing.JPanel tarjetaDevolucionesMes;
    private javax.swing.JPanel tarjetaProductos;
    private javax.swing.JPanel tarjetaPromocionesActivas;
    private javax.swing.JLabel valorClientes;
    private javax.swing.JLabel valorDevolucionesMes;
    private javax.swing.JLabel valorProductos;
    private javax.swing.JLabel valorPromocionesActivas;
    // End of variables declaration//GEN-END:variables
}
