/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.gamezone.ui;

/**
 *
 * @author USUARIO
 */
public class ProductDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProductDialog.class.getName());

    /**
     * Creates new form ProductDialog
     */
    public ProductDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        lblHeaderTitle = new javax.swing.JLabel();
        lblHeaderSubtitle = new javax.swing.JLabel();
        lblProductType = new javax.swing.JLabel();
        cmbProductType = new javax.swing.JComboBox<>();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        lblPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        lblStock = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        lblSpecificSection = new javax.swing.JLabel();
        lblSpecific1 = new javax.swing.JLabel();
        txtSpecific1 = new javax.swing.JTextField();
        lblSpecific2 = new javax.swing.JLabel();
        txtSpecific2 = new javax.swing.JTextField();
        lblSpecific3 = new javax.swing.JLabel();
        txtSpecific3 = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GameZone - Registrar Producto");
        setBackground(new java.awt.Color(255, 255, 255));
        setModal(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHeader.setBackground(new java.awt.Color(20, 40, 75));
        pnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeaderTitle.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblHeaderTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblHeaderTitle.setText("Registrar Nuevo Producto");
        pnlHeader.add(lblHeaderTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 15, 320, 25));

        lblHeaderSubtitle.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblHeaderSubtitle.setForeground(new java.awt.Color(210, 220, 235));
        lblHeaderSubtitle.setText("Ingresa los datos generales y específicos del producto");
        pnlHeader.add(lblHeaderSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 360, 20));

        getContentPane().add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 75));

        lblProductType.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblProductType.setForeground(new java.awt.Color(31, 41, 55));
        lblProductType.setText("Tipo de producto:*");
        getContentPane().add(lblProductType, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 200, 20));

        cmbProductType.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbProductType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Videojuego", "Consola" }));
        cmbProductType.addActionListener(this::cmbProductTypeActionPerformed);
        getContentPane().add(cmbProductType, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 115, 440, 35));

        lblId.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblId.setText("ID Producto:*");
        getContentPane().add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 205, 20));

        txtId.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 185, 205, 35));

        lblTitle.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblTitle.setText("Título / Nombre:*");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 205, 20));

        txtTitle.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(txtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 255, 205, 35));

        lblPrice.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblPrice.setText("Precio ($):*");
        getContentPane().add(lblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 160, 205, 20));

        txtPrice.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 185, 205, 35));

        lblStock.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblStock.setText("Stock inicial:*");
        getContentPane().add(lblStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 230, 205, 20));

        txtStock.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 255, 205, 35));

        lblSpecificSection.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblSpecificSection.setForeground(new java.awt.Color(30, 136, 229));
        lblSpecificSection.setText("Características específicas:");
        getContentPane().add(lblSpecificSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 305, 440, 20));

        lblSpecific1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblSpecific1.setText("Plataforma:*");
        getContentPane().add(lblSpecific1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 440, 20));

        txtSpecific1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(txtSpecific1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 355, 440, 35));

        lblSpecific2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblSpecific2.setText("Género:*");
        getContentPane().add(lblSpecific2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 440, 20));

        txtSpecific2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(txtSpecific2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 425, 440, 35));

        lblSpecific3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblSpecific3.setText("Clasificación de edad:*");
        getContentPane().add(lblSpecific3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 440, 20));

        txtSpecific3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(txtSpecific3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 495, 440, 35));

        btnCancel.setBackground(new java.awt.Color(229, 57, 53));
        btnCancel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancelar");
        btnCancel.setBorderPainted(false);
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.setFocusPainted(false);
        btnCancel.addActionListener(this::btnCancelActionPerformed);
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 555, 130, 40));

        btnSave.setBackground(new java.awt.Color(46, 125, 50));
        btnSave.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Guardar");
        btnSave.setBorderPainted(false);
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.setFocusPainted(false);
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 555, 130, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void cmbProductTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProductTypeActionPerformed
        String selected = cmbProductType.getSelectedItem().toString().trim();
        
        if ("Consola".equals(cmbProductType.getSelectedItem())) {          
           lblSpecific1.setText("Marca:*");
           lblSpecific2.setText("Modelo:*");
           lblSpecific3.setText("Generación:*");
       } else {
           lblSpecific1.setText("Plataforma:*");
           lblSpecific2.setText("Género:*");
           lblSpecific3.setText("Clasificación de edad:*");
       }
    }//GEN-LAST:event_cmbProductTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ProductDialog dialog = new ProductDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbProductType;
    private javax.swing.JLabel lblHeaderSubtitle;
    private javax.swing.JLabel lblHeaderTitle;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblProductType;
    private javax.swing.JLabel lblSpecific1;
    private javax.swing.JLabel lblSpecific2;
    private javax.swing.JLabel lblSpecific3;
    private javax.swing.JLabel lblSpecificSection;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSpecific1;
    private javax.swing.JTextField txtSpecific2;
    private javax.swing.JTextField txtSpecific3;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
