package com.gamezone.ui;

import com.gamezone.model.Product;
import com.gamezone.service.ProductService;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class ProductPanel extends javax.swing.JPanel {

    private ProductService productService;

    /**
     * Creates new form ProductPanel
     */
    public ProductPanel() {
        initComponents();
        setupEvents();
    }

    public ProductPanel(ProductService productService) {
        this.productService = productService;
        initComponents();
        setupEvents();
        loadProducts();
    }

    private void setupEvents() {
        btnBuscarProducto.addActionListener(e -> searchProducts());
        txtBuscarProducto.addActionListener(e -> searchProducts());
    }

    public void loadProducts() {
        if (productService == null) return;
        DefaultTableModel model = (DefaultTableModel) tblProductos.getModel();
        model.setRowCount(0);
        for (Product p : productService.listAllProducts()) {
            model.addRow(new Object[]{
                p.getId(),
                p.getTitle(),
                String.format("$%,.0f", p.getPrice()),
                p.getStock()
            });
        }
    }

    private void searchProducts() {
        if (productService == null) return;
        String query = txtBuscarProducto.getText().trim().toLowerCase();
        if (query.isEmpty()) {
            loadProducts();
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblProductos.getModel();
        model.setRowCount(0);
        for (Product p : productService.listAllProducts()) {
            if (p.getId().toLowerCase().contains(query) || p.getTitle().toLowerCase().contains(query)) {
                model.addRow(new Object[]{
                    p.getId(),
                    p.getTitle(),
                    String.format("$%,.0f", p.getPrice()),
                    p.getStock()
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloProductos = new javax.swing.JLabel();
        lblSubtituloProductos = new javax.swing.JLabel();
        btnNuevoProducto = new javax.swing.JButton();
        pnlContenidoProductos = new javax.swing.JPanel();
        lblBuscarProducto = new javax.swing.JLabel();
        txtBuscarProducto = new javax.swing.JTextField();
        btnBuscarProducto = new javax.swing.JButton();
        spTablaProductos = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();

        setBackground(new java.awt.Color(245, 247, 250));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloProductos.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        lblTituloProductos.setForeground(new java.awt.Color(31, 41, 55));
        lblTituloProductos.setText("Productos");
        add(lblTituloProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 35, 180, 35));

        lblSubtituloProductos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSubtituloProductos.setForeground(new java.awt.Color(107, 114, 128));
        lblSubtituloProductos.setText("Gestiona el inventario de GameZone.");
        add(lblSubtituloProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 75, 250, 25));

        btnNuevoProducto.setBackground(new java.awt.Color(30, 136, 229));
        btnNuevoProducto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnNuevoProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoProducto.setText("+ Nuevo producto");
        btnNuevoProducto.setBorderPainted(false);
        btnNuevoProducto.setFocusPainted(false);
        btnNuevoProducto.addActionListener(this::btnNuevoProductoActionPerformed);
        add(btnNuevoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, 165, 40));

        pnlContenidoProductos.setBackground(new java.awt.Color(255, 255, 255));
        pnlContenidoProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBuscarProducto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblBuscarProducto.setForeground(new java.awt.Color(31, 41, 55));
        lblBuscarProducto.setText("Buscar producto");
        pnlContenidoProductos.add(lblBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 25, 130, 25));

        txtBuscarProducto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtBuscarProducto.setForeground(new java.awt.Color(31, 41, 55));
        pnlContenidoProductos.add(txtBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 20, 300, 35));

        btnBuscarProducto.setBackground(new java.awt.Color(30, 136, 229));
        btnBuscarProducto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnBuscarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarProducto.setText("Buscar");
        btnBuscarProducto.setBorderPainted(false);
        btnBuscarProducto.setFocusPainted(false);
        pnlContenidoProductos.add(btnBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 110, 35));

        spTablaProductos.setBackground(new java.awt.Color(255, 255, 255));

        tblProductos.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        tblProductos.setForeground(new java.awt.Color(31, 41, 55));
        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Titulo", "Precio", "Stock"
            }
        ));
        spTablaProductos.setViewportView(tblProductos);

        pnlContenidoProductos.add(spTablaProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 85, 870, 330));

        add(pnlContenidoProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 920, 450));
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        java.awt.Frame parentFrame = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);
        ProductDialog dialog = new ProductDialog(parentFrame, true, productService, this);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnNuevoProductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnNuevoProducto;
    private javax.swing.JLabel lblBuscarProducto;
    private javax.swing.JLabel lblSubtituloProductos;
    private javax.swing.JLabel lblTituloProductos;
    private javax.swing.JPanel pnlContenidoProductos;
    private javax.swing.JScrollPane spTablaProductos;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtBuscarProducto;
    // End of variables declaration//GEN-END:variables
}
