/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.gamezone.ui;

/**
 *
 * @author USUARIO
 */
public class PromotionPanel extends javax.swing.JPanel {

    /**
     * Creates new form PromotionPanel
     */
    public PromotionPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloPromociones = new javax.swing.JLabel();
        lblSubtituloPromociones = new javax.swing.JLabel();
        btnNuevaPromocion = new javax.swing.JButton();
        pnlContenidoPromociones = new javax.swing.JPanel();
        lblBuscarPromocion = new javax.swing.JLabel();
        txtBuscarPromocion = new javax.swing.JTextField();
        btnBuscarPromocion = new javax.swing.JButton();
        chkSoloVigentes = new javax.swing.JCheckBox();
        JsPromociones = new javax.swing.JScrollPane();
        tblPromociones = new javax.swing.JTable();

        setBackground(new java.awt.Color(245, 247, 250));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloPromociones.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        lblTituloPromociones.setForeground(new java.awt.Color(31, 41, 55));
        lblTituloPromociones.setText("Promociones");
        add(lblTituloPromociones, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 35, 200, 35));

        lblSubtituloPromociones.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSubtituloPromociones.setForeground(new java.awt.Color(107, 114, 128));
        lblSubtituloPromociones.setText("Gestión de campañas de descuento y ofertas de GameZone");
        add(lblSubtituloPromociones, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 75, 450, 25));

        btnNuevaPromocion.setBackground(new java.awt.Color(30, 136, 229));
        btnNuevaPromocion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnNuevaPromocion.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevaPromocion.setText("+ Nueva promoción");
        btnNuevaPromocion.setBorderPainted(false);
        btnNuevaPromocion.setFocusPainted(false);
        add(btnNuevaPromocion, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, 185, 40));

        pnlContenidoPromociones.setBackground(new java.awt.Color(255, 255, 255));
        pnlContenidoPromociones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBuscarPromocion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblBuscarPromocion.setForeground(new java.awt.Color(31, 41, 55));
        lblBuscarPromocion.setText("Buscar");
        pnlContenidoPromociones.add(lblBuscarPromocion, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 25, 60, 25));

        txtBuscarPromocion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        pnlContenidoPromociones.add(txtBuscarPromocion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 280, 35));

        btnBuscarPromocion.setBackground(new java.awt.Color(30, 136, 229));
        btnBuscarPromocion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnBuscarPromocion.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarPromocion.setText("Buscar");
        btnBuscarPromocion.setBorderPainted(false);
        btnBuscarPromocion.setFocusPainted(false);
        pnlContenidoPromociones.add(btnBuscarPromocion, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 20, 100, 35));

        chkSoloVigentes.setBackground(new java.awt.Color(255, 255, 255));
        chkSoloVigentes.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        chkSoloVigentes.setForeground(new java.awt.Color(31, 41, 55));
        chkSoloVigentes.setText("Mostrar solo promociones vigentes");
        chkSoloVigentes.setFocusPainted(false);
        pnlContenidoPromociones.add(chkSoloVigentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 25, 260, 25));

        JsPromociones.setWheelScrollingEnabled(false);

        tblPromociones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Tipo", "Descuento", "Fecha Inicio", "Fecha Fin", "Estado"
            }
        ));
        JsPromociones.setViewportView(tblPromociones);

        pnlContenidoPromociones.add(JsPromociones, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 85, 870, 400));

        add(pnlContenidoPromociones, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 920, 520));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JsPromociones;
    private javax.swing.JButton btnBuscarPromocion;
    private javax.swing.JButton btnNuevaPromocion;
    private javax.swing.JCheckBox chkSoloVigentes;
    private javax.swing.JLabel lblBuscarPromocion;
    private javax.swing.JLabel lblSubtituloPromociones;
    private javax.swing.JLabel lblTituloPromociones;
    private javax.swing.JPanel pnlContenidoPromociones;
    private javax.swing.JTable tblPromociones;
    private javax.swing.JTextField txtBuscarPromocion;
    // End of variables declaration//GEN-END:variables
}
