/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.gamezone.ui;

/**
 *
 * @author USUARIO
 */
public class PromotionDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PromotionDialog.class.getName());

    /**
     * Creates new form PromotionDialog
     */
    public PromotionDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblHeaderTitle = new javax.swing.JLabel();
        lblHeaderSubtitle = new javax.swing.JLabel();
        lblPromotionType = new javax.swing.JLabel();
        cmbPromotionType = new javax.swing.JComboBox<>();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblStartDate = new javax.swing.JLabel();
        txtStartDate = new javax.swing.JTextField();
        lblEndDate = new javax.swing.JLabel();
        txtEndDate = new javax.swing.JTextField();
        lblDiscount = new javax.swing.JLabel();
        txtDiscount = new javax.swing.JTextField();
        lblCondition = new javax.swing.JLabel();
        txtCondition = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GameZone - Registrar Promoción");
        setBackground(new java.awt.Color(255, 255, 255));
        setModal(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(20, 40, 75));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeaderTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblHeaderTitle.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblHeaderTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblHeaderTitle.setText("Registrar Nueva Promoción");
        jPanel1.add(lblHeaderTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 15, 320, 25));

        lblHeaderSubtitle.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblHeaderSubtitle.setForeground(new java.awt.Color(210, 220, 235));
        lblHeaderSubtitle.setText("Define las reglas de descuento y fechas de vigencia");
        jPanel1.add(lblHeaderSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 360, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 75));

        lblPromotionType.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblPromotionType.setForeground(new java.awt.Color(31, 41, 55));
        lblPromotionType.setText("Tipo de promoción:*");
        getContentPane().add(lblPromotionType, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 200, 20));

        cmbPromotionType.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cmbPromotionType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Porcentaje", "Categoría", "Volumen" }));
        cmbPromotionType.addActionListener(this::cmbPromotionTypeActionPerformed);
        getContentPane().add(cmbPromotionType, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 115, 440, 35));

        lblId.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblId.setText("ID Promoción:*");
        getContentPane().add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 205, 20));

        txtId.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 185, 205, 35));

        lblName.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblName.setText("Nombre de la promoción:*");
        getContentPane().add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 160, 205, 20));

        txtName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 185, 205, 35));

        lblStartDate.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblStartDate.setText("Fecha inicio (AAAA-MM-DD):*");
        getContentPane().add(lblStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 205, 20));

        txtStartDate.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtStartDate.setText("2026-09-01");
        getContentPane().add(txtStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 255, 205, 35));

        lblEndDate.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblEndDate.setText("Fecha fin (AAAA-MM-DD):*");
        getContentPane().add(lblEndDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 230, 205, 20));

        txtEndDate.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtEndDate.setText("2026-09-30");
        getContentPane().add(txtEndDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 255, 205, 35));

        lblDiscount.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblDiscount.setText("Descuento (%):*");
        getContentPane().add(lblDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 205, 20));

        txtDiscount.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(txtDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 325, 205, 35));

        lblCondition.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblCondition.setText("Condición adicional:");
        getContentPane().add(lblCondition, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 300, 240, 20));

        txtCondition.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCondition.setText("N/A");
        txtCondition.setEnabled(false);
        getContentPane().add(txtCondition, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 325, 205, 35));

        btnCancel.setBackground(new java.awt.Color(229, 57, 53));
        btnCancel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancelar");
        btnCancel.setBorderPainted(false);
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.setFocusPainted(false);
        btnCancel.addActionListener(this::btnCancelActionPerformed);
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 130, 40));

        btnSave.setBackground(new java.awt.Color(46, 125, 50));
        btnSave.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Guardar");
        btnSave.setBorderPainted(false);
        btnSave.setFocusPainted(false);
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 130, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void cmbPromotionTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPromotionTypeActionPerformed
               String selected = cmbPromotionType.getSelectedItem().toString().
                trim();

        if ("Categoría".equalsIgnoreCase(selected)) {
            lblCondition.setText("Categoría (VIDEOGAME/CONSOLE):*");
            txtCondition.setText("VIDEOGAME");
            txtCondition.setEnabled(true);
        } else if ("Volumen".equalsIgnoreCase(selected)) {
            lblCondition.setText("Cantidad mínima de productos:*");
            txtCondition.setText("3");
            txtCondition.setEnabled(true);
        } else { // Porcentaje
            lblCondition.setText("Condición adicional:");
            txtCondition.setText("N/A");
            txtCondition.setEnabled(false);
        }

    }//GEN-LAST:event_cmbPromotionTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                PromotionDialog dialog = new PromotionDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbPromotionType;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCondition;
    private javax.swing.JLabel lblDiscount;
    private javax.swing.JLabel lblEndDate;
    private javax.swing.JLabel lblHeaderSubtitle;
    private javax.swing.JLabel lblHeaderTitle;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPromotionType;
    private javax.swing.JLabel lblStartDate;
    private javax.swing.JTextField txtCondition;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtEndDate;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtStartDate;
    // End of variables declaration//GEN-END:variables
}
