/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.gamezone.ui;

/**
 *
 * @author USUARIO
 */
public class ReportsPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportsPanel
     */
    public ReportsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblReportsTitle = new javax.swing.JLabel();
        lblReportsSubtitle = new javax.swing.JLabel();
        pnlReportsContent = new javax.swing.JPanel();
        lblMonth = new javax.swing.JLabel();
        cmbMonth = new javax.swing.JComboBox<>();
        lblYear = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        btnGenerateReport = new javax.swing.JButton();
        pnlTotalSalesCard = new javax.swing.JPanel();
        lblTotalSalesTitle = new javax.swing.JLabel();
        lblTotalSalesValue = new javax.swing.JLabel();
        pnlTotalReturnsCard = new javax.swing.JPanel();
        lblTotalReturnsTitle = new javax.swing.JLabel();
        lblTotalReturnsValue = new javax.swing.JLabel();
        pnlNetBalanceCard = new javax.swing.JPanel();
        lblNetBalanceTitle = new javax.swing.JLabel();
        lblNetBalanceValue = new javax.swing.JLabel();
        JsReports = new javax.swing.JScrollPane();
        tblReports = new javax.swing.JTable();

        setBackground(new java.awt.Color(245, 247, 250));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblReportsTitle.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        lblReportsTitle.setForeground(new java.awt.Color(31, 41, 55));
        lblReportsTitle.setText("Reportes");
        add(lblReportsTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 35, 200, 35));

        lblReportsSubtitle.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblReportsSubtitle.setForeground(new java.awt.Color(107, 114, 128));
        lblReportsSubtitle.setText("Balance financiero mensual y métricas de rendimiento");
        add(lblReportsSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 75, 450, 25));

        pnlReportsContent.setBackground(new java.awt.Color(255, 255, 255));
        pnlReportsContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMonth.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMonth.setForeground(new java.awt.Color(31, 41, 55));
        lblMonth.setText("Mes:");
        pnlReportsContent.add(lblMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 25, 45, 25));

        cmbMonth.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        cmbMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        pnlReportsContent.add(cmbMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 20, 140, 35));

        lblYear.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblYear.setForeground(new java.awt.Color(31, 41, 55));
        lblYear.setText("Año: ");
        pnlReportsContent.add(lblYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 25, 40, 25));

        txtYear.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtYear.setText("2026");
        pnlReportsContent.add(txtYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 20, 90, 35));

        btnGenerateReport.setBackground(new java.awt.Color(30, 136, 229));
        btnGenerateReport.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnGenerateReport.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerateReport.setText("Generar balance");
        btnGenerateReport.setBorderPainted(false);
        btnGenerateReport.setFocusPainted(false);
        pnlReportsContent.add(btnGenerateReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 160, 35));

        pnlTotalSalesCard.setBackground(new java.awt.Color(248, 250, 252));
        pnlTotalSalesCard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 198, 218), 2));
        pnlTotalSalesCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTotalSalesTitle.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblTotalSalesTitle.setForeground(new java.awt.Color(107, 114, 128));
        lblTotalSalesTitle.setText("Total Ventas");
        pnlTotalSalesCard.add(lblTotalSalesTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 12, 150, 20));

        lblTotalSalesValue.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        lblTotalSalesValue.setForeground(new java.awt.Color(31, 41, 55));
        lblTotalSalesValue.setText("$0.00");
        pnlTotalSalesCard.add(lblTotalSalesValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 38, 240, 35));

        pnlReportsContent.add(pnlTotalSalesCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 75, 270, 90));

        pnlTotalReturnsCard.setBackground(new java.awt.Color(248, 250, 252));
        pnlTotalReturnsCard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(239, 83, 80), 2));
        pnlTotalReturnsCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTotalReturnsTitle.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblTotalReturnsTitle.setText("Total Devoluciones");
        pnlTotalReturnsCard.add(lblTotalReturnsTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 12, 150, 20));

        lblTotalReturnsValue.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        lblTotalReturnsValue.setForeground(new java.awt.Color(31, 41, 55));
        lblTotalReturnsValue.setText("$0.00");
        pnlTotalReturnsCard.add(lblTotalReturnsValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 38, 240, 35));

        pnlReportsContent.add(pnlTotalReturnsCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 75, 270, 90));

        pnlNetBalanceCard.setBackground(new java.awt.Color(248, 250, 252));
        pnlNetBalanceCard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(46, 125, 50), 2));
        pnlNetBalanceCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNetBalanceTitle.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblNetBalanceTitle.setText("Balance Neto (Ganancia)");
        pnlNetBalanceCard.add(lblNetBalanceTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 12, 180, 20));

        lblNetBalanceValue.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        lblNetBalanceValue.setForeground(new java.awt.Color(46, 125, 50));
        lblNetBalanceValue.setText("$0.00");
        pnlNetBalanceCard.add(lblNetBalanceValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 38, 240, 35));

        pnlReportsContent.add(pnlNetBalanceCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(625, 75, 270, 90));

        tblReports.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        tblReports.setForeground(new java.awt.Color(31, 41, 55));
        tblReports.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Transacción", "Fecha", "Tipo", "Cliente", "Monto ($)"
            }
        ));
        JsReports.setViewportView(tblReports);

        pnlReportsContent.add(JsReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 185, 870, 315));

        add(pnlReportsContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 920, 520));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JsReports;
    private javax.swing.JButton btnGenerateReport;
    private javax.swing.JComboBox<String> cmbMonth;
    private javax.swing.JLabel lblMonth;
    private javax.swing.JLabel lblNetBalanceTitle;
    private javax.swing.JLabel lblNetBalanceValue;
    private javax.swing.JLabel lblReportsSubtitle;
    private javax.swing.JLabel lblReportsTitle;
    private javax.swing.JLabel lblTotalReturnsTitle;
    private javax.swing.JLabel lblTotalReturnsValue;
    private javax.swing.JLabel lblTotalSalesTitle;
    private javax.swing.JLabel lblTotalSalesValue;
    private javax.swing.JLabel lblYear;
    private javax.swing.JPanel pnlNetBalanceCard;
    private javax.swing.JPanel pnlReportsContent;
    private javax.swing.JPanel pnlTotalReturnsCard;
    private javax.swing.JPanel pnlTotalSalesCard;
    private javax.swing.JTable tblReports;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
