/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.gamezone.ui;

/**
 *
 * @author USUARIO
 */
public class ReturnPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReturnPanel
     */
    public ReturnPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloDevoluciones = new javax.swing.JLabel();
        lblSubtituloDevoluciones = new javax.swing.JLabel();
        btnNuevaDevolucion = new javax.swing.JButton();
        pnlContenidoDevoluciones = new javax.swing.JPanel();
        lblBuscarDevolucion = new javax.swing.JLabel();
        txtBuscarDevolucion = new javax.swing.JTextField();
        btnBuscarDevolucion = new javax.swing.JButton();
        btnVerComprobante = new javax.swing.JButton();
        JsReturn = new javax.swing.JScrollPane();
        tblReturns = new javax.swing.JTable();

        setBackground(new java.awt.Color(245, 247, 250));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloDevoluciones.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        lblTituloDevoluciones.setForeground(new java.awt.Color(31, 41, 55));
        lblTituloDevoluciones.setText("Devoluciones");
        add(lblTituloDevoluciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 35, 200, 35));

        lblSubtituloDevoluciones.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSubtituloDevoluciones.setForeground(new java.awt.Color(107, 114, 128));
        lblSubtituloDevoluciones.setText("Gestión de reembolsos y devoluciones de productos");
        add(lblSubtituloDevoluciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 75, 450, 25));

        btnNuevaDevolucion.setBackground(new java.awt.Color(30, 136, 229));
        btnNuevaDevolucion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnNuevaDevolucion.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevaDevolucion.setText("+ Nueva devolución");
        btnNuevaDevolucion.setBorderPainted(false);
        btnNuevaDevolucion.setFocusPainted(false);
        add(btnNuevaDevolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, 185, 40));

        pnlContenidoDevoluciones.setBackground(new java.awt.Color(255, 255, 255));
        pnlContenidoDevoluciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBuscarDevolucion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblBuscarDevolucion.setForeground(new java.awt.Color(31, 41, 55));
        lblBuscarDevolucion.setText("Buscar");
        pnlContenidoDevoluciones.add(lblBuscarDevolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 25, 60, 25));

        txtBuscarDevolucion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        pnlContenidoDevoluciones.add(txtBuscarDevolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 300, 35));

        btnBuscarDevolucion.setBackground(new java.awt.Color(30, 136, 229));
        btnBuscarDevolucion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnBuscarDevolucion.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarDevolucion.setText("Buscar");
        btnBuscarDevolucion.setBorderPainted(false);
        btnBuscarDevolucion.setFocusPainted(false);
        pnlContenidoDevoluciones.add(btnBuscarDevolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 20, 100, 35));

        btnVerComprobante.setBackground(new java.awt.Color(38, 198, 218));
        btnVerComprobante.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnVerComprobante.setForeground(new java.awt.Color(255, 255, 255));
        btnVerComprobante.setText("Ver comprobante");
        btnVerComprobante.setBorderPainted(false);
        btnVerComprobante.setFocusPainted(false);
        pnlContenidoDevoluciones.add(btnVerComprobante, new org.netbeans.lib.awtextra.AbsoluteConstraints(735, 20, 160, 35));

        tblReturns.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        tblReturns.setForeground(new java.awt.Color(31, 41, 55));
        tblReturns.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Devolución", "Fecha", "ID Venta", "Cliente", "Productos Devueltos", "Motivo", "Reembolso ($)"
            }
        ));
        JsReturn.setViewportView(tblReturns);

        pnlContenidoDevoluciones.add(JsReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 85, 870, 400));

        add(pnlContenidoDevoluciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 920, 520));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JsReturn;
    private javax.swing.JButton btnBuscarDevolucion;
    private javax.swing.JButton btnNuevaDevolucion;
    private javax.swing.JButton btnVerComprobante;
    private javax.swing.JLabel lblBuscarDevolucion;
    private javax.swing.JLabel lblSubtituloDevoluciones;
    private javax.swing.JLabel lblTituloDevoluciones;
    private javax.swing.JPanel pnlContenidoDevoluciones;
    private javax.swing.JTable tblReturns;
    private javax.swing.JTextField txtBuscarDevolucion;
    // End of variables declaration//GEN-END:variables
}
