/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.gamezone.ui;

/**
 *
 * @author USUARIO
 */
public class ReturnDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReturnDialog.class.getName());

    /**
     * Creates new form ReturnDialog
     */
    public ReturnDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblHeaderTitle = new javax.swing.JLabel();
        lblHeaderSubtitle = new javax.swing.JLabel();
        lblSaleId = new javax.swing.JLabel();
        txtSaleId = new javax.swing.JTextField();
        lblProducts = new javax.swing.JLabel();
        txtProducts = new javax.swing.JTextField();
        lblReason = new javax.swing.JLabel();
        txtReason = new javax.swing.JTextField();
        lblRefundAmount = new javax.swing.JLabel();
        txtRefundAmount = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GameZone - Registrar Devolución");
        setBackground(new java.awt.Color(255, 255, 255));
        setModal(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(20, 40, 75));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeaderTitle.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblHeaderTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblHeaderTitle.setText("Registrar Devolución");
        jPanel1.add(lblHeaderTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 15, 300, 25));

        lblHeaderSubtitle.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblHeaderSubtitle.setForeground(new java.awt.Color(210, 220, 235));
        lblHeaderSubtitle.setText("Reintegro de productos y reposición de inventario");
        jPanel1.add(lblHeaderSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 360, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 75));

        lblSaleId.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblSaleId.setForeground(new java.awt.Color(31, 41, 55));
        lblSaleId.setText("ID de la Venta original:*");
        getContentPane().add(lblSaleId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 95, 440, 20));

        txtSaleId.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(txtSaleId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 440, 35));

        lblProducts.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblProducts.setText("Productos a devolver (IDs o nombres):*");
        getContentPane().add(lblProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 165, 440, 20));

        txtProducts.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(txtProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 440, 35));

        lblReason.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblReason.setText("Motivo de la devolución:*");
        getContentPane().add(lblReason, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 235, 440, 20));

        txtReason.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(txtReason, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 440, 35));

        lblRefundAmount.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblRefundAmount.setText("Monto a reembolsar ($):*");
        getContentPane().add(lblRefundAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 305, 440, 20));

        txtRefundAmount.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtRefundAmount.setText("0.00");
        getContentPane().add(txtRefundAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 440, 35));

        btnCancel.setBackground(new java.awt.Color(229, 57, 53));
        btnCancel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancelar");
        btnCancel.setBorderPainted(false);
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.setFocusPainted(false);
        btnCancel.addActionListener(this::btnCancelActionPerformed);
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 395, 130, 40));

        btnSave.setBackground(new java.awt.Color(46, 125, 50));
        btnSave.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Registrar");
        btnSave.setBorderPainted(false);
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.setFocusCycleRoot(true);
        btnSave.setFocusPainted(false);
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 395, 130, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
        
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ReturnDialog dialog = new ReturnDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHeaderSubtitle;
    private javax.swing.JLabel lblHeaderTitle;
    private javax.swing.JLabel lblProducts;
    private javax.swing.JLabel lblReason;
    private javax.swing.JLabel lblRefundAmount;
    private javax.swing.JLabel lblSaleId;
    private javax.swing.JTextField txtProducts;
    private javax.swing.JTextField txtReason;
    private javax.swing.JTextField txtRefundAmount;
    private javax.swing.JTextField txtSaleId;
    // End of variables declaration//GEN-END:variables
}
