/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.gamezone.ui;

/**
 *
 * @author USUARIO
 */
public class SaleDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SaleDialog.class.getName());

    private com.gamezone.service.SaleService saleService;
    private com.gamezone.service.PersonService personService;
    private com.gamezone.service.ProductService productService;
    private com.gamezone.service.AccessoryService accessoryService;
    private com.gamezone.service.PromotionService promotionService;
    private SalePanel salePanel;

    private static class CartItem {
        com.gamezone.model.Product product;
        boolean extendedWarranty;

        CartItem(com.gamezone.model.Product product, boolean extendedWarranty) {
            this.product = product;
            this.extendedWarranty = extendedWarranty;
        }
    }

    private final java.util.List<CartItem> cartItems = new java.util.ArrayList<>();
    private final java.util.List<com.gamezone.model.Customer> customerList = new java.util.ArrayList<>();
    private final java.util.List<com.gamezone.model.Seller> sellerList = new java.util.ArrayList<>();
    private final java.util.List<com.gamezone.model.Product> catalogProducts = new java.util.ArrayList<>();

    /**
     * Creates new form SaleDialog
     */
    public SaleDialog(java.awt.Frame parent, boolean modal) {
        this(parent, modal, null, null, null, null, null, null);
    }

    public SaleDialog(java.awt.Frame parent, boolean modal,
                      com.gamezone.service.SaleService saleService,
                      com.gamezone.service.PersonService personService,
                      com.gamezone.service.ProductService productService,
                      com.gamezone.service.AccessoryService accessoryService,
                      com.gamezone.service.PromotionService promotionService,
                      SalePanel salePanel) {
        super(parent, modal);
        this.saleService = saleService;
        this.personService = personService;
        this.productService = productService;
        this.accessoryService = accessoryService;
        this.promotionService = promotionService;
        this.salePanel = salePanel;
        initComponents();
        setLocationRelativeTo(null);
        populateDropdowns();
        setupEventListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblHeaderTitle = new javax.swing.JLabel();
        lblHeaderSubtitle = new javax.swing.JLabel();
        lblCustomer = new javax.swing.JLabel();
        cmbCustomer = new javax.swing.JComboBox<>();
        lblSeller = new javax.swing.JLabel();
        cmbSeller = new javax.swing.JComboBox<>();
        lblSelectProduct = new javax.swing.JLabel();
        cmbProduct = new javax.swing.JComboBox<>();
        chkExtendedWarranty = new javax.swing.JCheckBox();
        btnAddProduct = new javax.swing.JButton();
        spSaleItems = new javax.swing.JScrollPane();
        tblSaleItems = new javax.swing.JTable();
        btnRemoveItem = new javax.swing.JButton();
        lblSubtotalText = new javax.swing.JLabel();
        lblSubtotalValue = new javax.swing.JLabel();
        lblDiscountText = new javax.swing.JLabel();
        lblDiscountValue = new javax.swing.JLabel();
        lblTotalText = new javax.swing.JLabel();
        lblTotalValue = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnConfirmSale = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GameZone - Registrar Nueva Venta");
        setBackground(new java.awt.Color(255, 255, 255));
        setModal(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(20, 40, 75));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeaderTitle.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblHeaderTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblHeaderTitle.setText("Registrar Nueva Venta");
        jPanel1.add(lblHeaderTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 15, 300, 25));

        lblHeaderSubtitle.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblHeaderSubtitle.setForeground(new java.awt.Color(210, 220, 235));
        lblHeaderSubtitle.setText("Punto de venta y facturación de GameZone");
        jPanel1.add(lblHeaderSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 320, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 75));

        lblCustomer.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblCustomer.setForeground(new java.awt.Color(31, 41, 55));
        lblCustomer.setText("Cliente:*");
        getContentPane().add(lblCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 150, 20));

        cmbCustomer.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        cmbCustomer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar cliente..." }));
        getContentPane().add(cmbCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 115, 310, 35));

        lblSeller.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblSeller.setForeground(new java.awt.Color(31, 41, 55));
        lblSeller.setText("Vendedor que atiende:*");
        getContentPane().add(lblSeller, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 180, 20));

        cmbSeller.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        cmbSeller.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar vendedor..." }));
        getContentPane().add(cmbSeller, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 115, 310, 35));

        lblSelectProduct.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblSelectProduct.setText("Agregar producto a la venta:*");
        getContentPane().add(lblSelectProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 165, 250, 20));

        cmbProduct.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        cmbProduct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar producto del catálogo..." }));
        getContentPane().add(cmbProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 370, 35));

        chkExtendedWarranty.setBackground(new java.awt.Color(255, 255, 255));
        chkExtendedWarranty.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        chkExtendedWarranty.setForeground(new java.awt.Color(31, 41, 55));
        chkExtendedWarranty.setText("Garantía Ext. (+10%)");
        getContentPane().add(chkExtendedWarranty, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 195, 150, 25));

        btnAddProduct.setBackground(new java.awt.Color(30, 136, 229));
        btnAddProduct.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnAddProduct.setForeground(new java.awt.Color(255, 255, 255));
        btnAddProduct.setText("+ Agregar");
        btnAddProduct.setBorderPainted(false);
        btnAddProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddProduct.setFocusPainted(false);
        getContentPane().add(btnAddProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 100, 35));

        tblSaleItems.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        tblSaleItems.setForeground(new java.awt.Color(31, 41, 55));
        tblSaleItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Producto", "Precio ($)", "Garantía"
            }
        ));
        spSaleItems.setViewportView(tblSaleItems);

        getContentPane().add(spSaleItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 640, 190));

        btnRemoveItem.setBackground(new java.awt.Color(240, 242, 245));
        btnRemoveItem.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnRemoveItem.setForeground(new java.awt.Color(229, 57, 53));
        btnRemoveItem.setText("Quitar seleccionado");
        btnRemoveItem.setBorderPainted(false);
        btnRemoveItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRemoveItem.setFocusPainted(false);
        getContentPane().add(btnRemoveItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 435, 160, 28));

        lblSubtotalText.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSubtotalText.setForeground(new java.awt.Color(107, 114, 128));
        lblSubtotalText.setText("Subtotal:");
        getContentPane().add(lblSubtotalText, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 475, 100, 20));

        lblSubtotalValue.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblSubtotalValue.setForeground(new java.awt.Color(31, 41, 55));
        lblSubtotalValue.setText("$0.00");
        getContentPane().add(lblSubtotalValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 475, 140, 20));

        lblDiscountText.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDiscountText.setForeground(new java.awt.Color(107, 114, 128));
        lblDiscountText.setText("Descuento:");
        getContentPane().add(lblDiscountText, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, 100, 20));

        lblDiscountValue.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblDiscountValue.setForeground(new java.awt.Color(229, 57, 53));
        lblDiscountValue.setText("-$0.00");
        getContentPane().add(lblDiscountValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 500, 140, 20));

        lblTotalText.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTotalText.setForeground(new java.awt.Color(31, 41, 55));
        lblTotalText.setText("TOTAL:");
        getContentPane().add(lblTotalText, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, 100, 25));

        lblTotalValue.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblTotalValue.setForeground(new java.awt.Color(46, 125, 50));
        lblTotalValue.setText("$0.00");
        getContentPane().add(lblTotalValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 530, 140, 25));

        btnCancel.setBackground(new java.awt.Color(229, 57, 53));
        btnCancel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancelar");
        btnCancel.setBorderPainted(false);
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.setFocusPainted(false);
        btnCancel.addActionListener(this::btnCancelActionPerformed);
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 580, 140, 42));

        btnConfirmSale.setBackground(new java.awt.Color(46, 125, 50));
        btnConfirmSale.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnConfirmSale.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmSale.setText("Confirmar Venta");
        btnConfirmSale.setBorderPainted(false);
        btnConfirmSale.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmSale.setFocusPainted(false);
        getContentPane().add(btnConfirmSale, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 580, 160, 42));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void populateDropdowns() {
        if (personService != null) {
            cmbCustomer.removeAllItems();
            cmbCustomer.addItem("Seleccionar cliente...");
            customerList.clear();
            for (com.gamezone.model.Customer c : personService.listAllCustomers()) {
                customerList.add(c);
                cmbCustomer.addItem(c.getId() + " - " + c.getFullName());
            }

            cmbSeller.removeAllItems();
            cmbSeller.addItem("Seleccionar vendedor...");
            sellerList.clear();
            for (com.gamezone.model.Seller s : personService.listAllSellers()) {
                sellerList.add(s);
                cmbSeller.addItem(s.getId() + " - " + s.getFullName() + " (" + s.getEmployeecode() + ")");
            }
        }

        cmbProduct.removeAllItems();
        cmbProduct.addItem("Seleccionar producto del catálogo...");
        catalogProducts.clear();

        if (productService != null) {
            for (com.gamezone.model.Product p : productService.listAllProducts()) {
                catalogProducts.add(p);
                String tag = (p instanceof com.gamezone.model.Console) ? "[Consola]" : "[Videojuego]";
                cmbProduct.addItem(tag + " " + p.getId() + " - " + p.getTitle() + " ($" + p.getPrice() + ") [Stock: " + p.getStock() + "]");
            }
        }

        if (accessoryService != null) {
            for (com.gamezone.model.Accessory a : accessoryService.listAllaccessories()) {
                catalogProducts.add(a);
                cmbProduct.addItem("[Accesorio] " + a.getId() + " - " + a.getTitle() + " ($" + a.getPrice() + ") [Stock: " + a.getStock() + "]");
            }
        }
    }

    private void setupEventListeners() {
        btnAddProduct.addActionListener(e -> addProductToCart());
        btnRemoveItem.addActionListener(e -> removeItemFromCart());
        btnConfirmSale.addActionListener(e -> confirmSale());

        cmbProduct.addActionListener(e -> {
            int idx = cmbProduct.getSelectedIndex();
            if (idx > 0 && (idx - 1) < catalogProducts.size()) {
                com.gamezone.model.Product selected = catalogProducts.get(idx - 1);
                boolean isConsole = selected instanceof com.gamezone.model.Console;
                chkExtendedWarranty.setEnabled(isConsole);
                if (!isConsole) {
                    chkExtendedWarranty.setSelected(false);
                }
            } else {
                chkExtendedWarranty.setEnabled(false);
                chkExtendedWarranty.setSelected(false);
            }
        });

        cmbCustomer.addActionListener(e -> updateTotals());
    }

    private void addProductToCart() {
        int idx = cmbProduct.getSelectedIndex();
        if (idx <= 0 || (idx - 1) >= catalogProducts.size()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor seleccione un producto del catálogo.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        com.gamezone.model.Product selected = catalogProducts.get(idx - 1);

        long alreadyInCart = cartItems.stream()
                .filter(ci -> ci.product.getId().equals(selected.getId()))
                .count();

        if (alreadyInCart >= selected.getStock()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Stock insuficiente para '" + selected.getTitle() + "'.\nDisponibles: " + selected.getStock() + " unidad(es).",
                    "Stock insuficiente", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        boolean extWarranty = chkExtendedWarranty.isSelected() && (selected instanceof com.gamezone.model.Console);
        cartItems.add(new CartItem(selected, extWarranty));

        renderCartTable();
        updateTotals();
    }

    private void removeItemFromCart() {
        int selectedRow = tblSaleItems.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor seleccione un ítem de la tabla para quitarlo.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (selectedRow >= 0 && selectedRow < cartItems.size()) {
            cartItems.remove(selectedRow);
            renderCartTable();
            updateTotals();
        }
    }

    private void renderCartTable() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblSaleItems.getModel();
        model.setRowCount(0);

        for (CartItem ci : cartItems) {
            String warrantyText = "No";
            if (ci.product instanceof com.gamezone.model.Console) {
                warrantyText = ci.extendedWarranty ? "Básica + Extendida" : "Básica";
            }
            model.addRow(new Object[]{
                ci.product.getId(),
                ci.product.getTitle(),
                String.format(java.util.Locale.US, "$%.2f", ci.product.getPrice()),
                warrantyText
            });
        }
    }

    private void updateTotals() {
        double subtotal = 0.0;
        for (CartItem ci : cartItems) {
            subtotal += ci.product.getPrice();
            if (ci.extendedWarranty && (ci.product instanceof com.gamezone.model.Console)) {
                subtotal += (ci.product.getPrice() * 0.10);
            }
        }

        double discount = 0.0;
        String promoName = null;

        if (cmbCustomer.getSelectedIndex() > 0 && !cartItems.isEmpty() && promotionService != null) {
            com.gamezone.model.Customer customer = customerList.get(cmbCustomer.getSelectedIndex() - 1);
            com.gamezone.model.Seller dummySeller = !sellerList.isEmpty() ? sellerList.get(0) : new com.gamezone.model.Seller();
            java.util.List<com.gamezone.model.Product> prods = cartItems.stream()
                    .map(ci -> ci.product)
                    .collect(java.util.stream.Collectors.toList());

            try {
                com.gamezone.model.Sale tempSale = new com.gamezone.model.Sale("TEMP", java.time.LocalDate.now(), customer, dummySeller, prods);
                tempSale.setSubtotal(subtotal);
                com.gamezone.model.Promotion bestPromo = promotionService.findBestPromotionFor(tempSale);
                if (bestPromo != null) {
                    discount = bestPromo.calculateDiscount(tempSale);
                    promoName = bestPromo.getName();
                }
            } catch (Exception ignored) {
            }
        }

        double total = Math.max(0.0, subtotal - discount);

        lblSubtotalValue.setText(String.format(java.util.Locale.US, "$%.2f", subtotal));
        if (discount > 0) {
            lblDiscountValue.setText(String.format(java.util.Locale.US, "-$%.2f (%s)", discount, promoName != null ? promoName : "Promo"));
        } else {
            lblDiscountValue.setText("-$0.00");
        }
        lblTotalValue.setText(String.format(java.util.Locale.US, "$%.2f", total));
    }

    private void confirmSale() {
        if (saleService == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Servicio de ventas no disponible.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (cmbCustomer.getSelectedIndex() <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor seleccione el cliente que realiza la compra.", "Cliente requerido", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (cmbSeller.getSelectedIndex() <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor seleccione el vendedor que atiende la venta.", "Vendedor requerido", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (cartItems.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe agregar al menos un producto a la venta.", "Venta vacía", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        com.gamezone.model.Customer customer = customerList.get(cmbCustomer.getSelectedIndex() - 1);
        com.gamezone.model.Seller seller = sellerList.get(cmbSeller.getSelectedIndex() - 1);
        java.util.List<com.gamezone.model.Product> products = cartItems.stream()
                .map(ci -> ci.product)
                .collect(java.util.stream.Collectors.toList());

        java.util.List<String> extWarrantyIds = cartItems.stream()
                .filter(ci -> ci.extendedWarranty)
                .map(ci -> ci.product.getId())
                .collect(java.util.stream.Collectors.toList());

        try {
            com.gamezone.model.Sale sale = saleService.registerSale(customer, seller, products, extWarrantyIds);
            javax.swing.JOptionPane.showMessageDialog(this,
                    "¡Venta registrada con éxito!\nID de Venta: " + sale.getId()
                    + "\nCliente: " + customer.getFullName()
                    + "\nVendedor: " + seller.getFullName()
                    + "\nTotal Facturado: $" + String.format(java.util.Locale.US, "%.2f", sale.getTotalAmount()),
                    "Venta Exitosa", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            java.awt.Frame parentFrame = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);
            DetailDialog detail = new DetailDialog(parentFrame, true);
            detail.setDocumentDetails("Recibo de Venta", "Factura de compra #" + sale.getId(), sale.generateReceipt());
            detail.setVisible(true);

            if (salePanel != null) {
                salePanel.loadSales();
            }
            dispose();
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al registrar la venta: " + ex.getMessage(), "Error en venta", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                SaleDialog dialog = new SaleDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirmSale;
    private javax.swing.JButton btnRemoveItem;
    private javax.swing.JCheckBox chkExtendedWarranty;
    private javax.swing.JComboBox<String> cmbCustomer;
    private javax.swing.JComboBox<String> cmbProduct;
    private javax.swing.JComboBox<String> cmbSeller;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCustomer;
    private javax.swing.JLabel lblDiscountText;
    private javax.swing.JLabel lblDiscountValue;
    private javax.swing.JLabel lblHeaderSubtitle;
    private javax.swing.JLabel lblHeaderTitle;
    private javax.swing.JLabel lblSelectProduct;
    private javax.swing.JLabel lblSeller;
    private javax.swing.JLabel lblSubtotalText;
    private javax.swing.JLabel lblSubtotalValue;
    private javax.swing.JLabel lblTotalText;
    private javax.swing.JLabel lblTotalValue;
    private javax.swing.JScrollPane spSaleItems;
    private javax.swing.JTable tblSaleItems;
    // End of variables declaration//GEN-END:variables
}
