/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.gamezone.ui;

/**
 *
 * @author USUARIO
 */
public class SalePanel extends javax.swing.JPanel {

    private com.gamezone.service.SaleService saleService;
    private com.gamezone.service.PersonService personService;
    private com.gamezone.service.ProductService productService;
    private com.gamezone.service.AccessoryService accessoryService;
    private com.gamezone.service.PromotionService promotionService;

    /**
     * Creates new form SalePanel
     */
    public SalePanel() {
        initComponents();
    }

    public SalePanel(com.gamezone.service.SaleService saleService,
                     com.gamezone.service.PersonService personService,
                     com.gamezone.service.ProductService productService,
                     com.gamezone.service.AccessoryService accessoryService,
                     com.gamezone.service.PromotionService promotionService) {
        this.saleService = saleService;
        this.personService = personService;
        this.productService = productService;
        this.accessoryService = accessoryService;
        this.promotionService = promotionService;
        initComponents();
        setupEvents();
        loadSales();
    }

    private void setupEvents() {
        btnBuscarVenta.addActionListener(e -> searchSales());
        txtBuscarVenta.addActionListener(e -> searchSales());
    }

    public void loadSales() {
        if (saleService == null) return;
        renderSalesTable(saleService.viewAllSales());
    }

    private void searchSales() {
        if (saleService == null) return;
        String query = txtBuscarVenta.getText().trim().toLowerCase();
        java.util.List<com.gamezone.model.Sale> all = saleService.viewAllSales();

        if (query.isEmpty()) {
            renderSalesTable(all);
            return;
        }

        java.util.List<com.gamezone.model.Sale> filtered = all.stream()
                .filter(s -> (s.getId() != null && s.getId().toLowerCase().contains(query))
                        || (s.getDate() != null && s.getDate().toString().contains(query))
                        || (s.getCustomer() != null && s.getCustomer().getFullName() != null && s.getCustomer().getFullName().toLowerCase().contains(query))
                        || (s.getCustomer() != null && s.getCustomer().getId() != null && s.getCustomer().getId().toLowerCase().contains(query))
                        || (s.getSeller() != null && s.getSeller().getFullName() != null && s.getSeller().getFullName().toLowerCase().contains(query))
                        || (s.getSeller() != null && s.getSeller().getEmployeecode() != null && s.getSeller().getEmployeecode().toLowerCase().contains(query)))
                .collect(java.util.stream.Collectors.toList());

        renderSalesTable(filtered);
    }

    private void renderSalesTable(java.util.List<com.gamezone.model.Sale> list) {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblVentas.getModel();
        model.setRowCount(0);

        for (com.gamezone.model.Sale s : list) {
            String customerName = (s.getCustomer() != null) ? s.getCustomer().getFullName() : "-";
            String sellerName = (s.getSeller() != null) ? s.getSeller().getFullName() : "-";
            String discountStr = (s.getDiscountAmount() > 0)
                    ? String.format(java.util.Locale.US, "-$%.2f", s.getDiscountAmount())
                    : "$0.00";

            model.addRow(new Object[]{
                s.getId(),
                s.getDate(),
                customerName,
                sellerName,
                String.format(java.util.Locale.US, "$%.2f", s.getSubtotal()),
                discountStr,
                String.format(java.util.Locale.US, "$%.2f", s.getTotalAmount())
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloVentas = new javax.swing.JLabel();
        lblSubtituloVentas = new javax.swing.JLabel();
        btnNuevaVenta = new javax.swing.JButton();
        pnlContenidoVentas = new javax.swing.JPanel();
        lblBuscarVenta = new javax.swing.JLabel();
        txtBuscarVenta = new javax.swing.JTextField();
        btnBuscarVenta = new javax.swing.JButton();
        btnVerDetalleVenta = new javax.swing.JButton();
        JsVentas = new javax.swing.JScrollPane();
        tblVentas = new javax.swing.JTable();

        setBackground(new java.awt.Color(245, 247, 250));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloVentas.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        lblTituloVentas.setForeground(new java.awt.Color(31, 41, 55));
        lblTituloVentas.setText("Ventas");
        add(lblTituloVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 35, 180, 35));

        lblSubtituloVentas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSubtituloVentas.setForeground(new java.awt.Color(107, 114, 128));
        lblSubtituloVentas.setText("Historial de transacciones y facturación de GameZone");
        add(lblSubtituloVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 75, 420, 25));

        btnNuevaVenta.setBackground(new java.awt.Color(30, 136, 229));
        btnNuevaVenta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnNuevaVenta.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevaVenta.setText("+ Nueva venta");
        btnNuevaVenta.setBorderPainted(false);
        btnNuevaVenta.setFocusPainted(false);
        btnNuevaVenta.addActionListener(this::btnNuevaVentaActionPerformed);
        add(btnNuevaVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, 165, 40));

        pnlContenidoVentas.setBackground(new java.awt.Color(255, 255, 255));
        pnlContenidoVentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBuscarVenta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblBuscarVenta.setForeground(new java.awt.Color(31, 41, 55));
        lblBuscarVenta.setText("Buscar venta");
        pnlContenidoVentas.add(lblBuscarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 25, 120, 25));

        txtBuscarVenta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        pnlContenidoVentas.add(txtBuscarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 20, 280, 35));

        btnBuscarVenta.setBackground(new java.awt.Color(30, 136, 229));
        btnBuscarVenta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnBuscarVenta.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarVenta.setText("Buscar");
        btnBuscarVenta.setBorderPainted(false);
        btnBuscarVenta.setFocusPainted(false);
        pnlContenidoVentas.add(btnBuscarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 100, 35));

        btnVerDetalleVenta.setBackground(new java.awt.Color(38, 198, 218));
        btnVerDetalleVenta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnVerDetalleVenta.setForeground(new java.awt.Color(255, 255, 255));
        btnVerDetalleVenta.setText("Ver detalle");
        btnVerDetalleVenta.setBorderPainted(false);
        btnVerDetalleVenta.setFocusPainted(false);
        btnVerDetalleVenta.addActionListener(this::btnVerDetalleVentaActionPerformed);
        pnlContenidoVentas.add(btnVerDetalleVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(765, 20, 130, 35));

        tblVentas.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        tblVentas.setForeground(new java.awt.Color(31, 41, 55));
        tblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Venta", "Fecha", "Cliente", "Vendedor", "Subtotal", "Descuento", "Total"
            }
        ));
        JsVentas.setViewportView(tblVentas);

        pnlContenidoVentas.add(JsVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 85, 870, 400));

        add(pnlContenidoVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 920, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaVentaActionPerformed
        java.awt.Frame parentFrame = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);
        SaleDialog dialog = new SaleDialog(parentFrame, true, saleService, personService, productService, accessoryService, promotionService, this);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnNuevaVentaActionPerformed

    private void btnVerDetalleVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDetalleVentaActionPerformed
        int selectedRow = tblVentas.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor seleccione una venta de la tabla para ver su detalle.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        String saleId = tblVentas.getValueAt(selectedRow, 0).toString();
        if (saleService == null) return;

        com.gamezone.model.Sale sale = saleService.findSaleById(saleId);
        if (sale == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "No se encontró la información de la venta seleccionada.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        java.awt.Frame parentFrame = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);
        DetailDialog dialog = new DetailDialog(parentFrame, true);
        dialog.setDocumentDetails("Recibo de Venta", "Detalle de compra y facturación #" + sale.getId(), sale.generateReceipt());
        dialog.setVisible(true);
    }//GEN-LAST:event_btnVerDetalleVentaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JsVentas;
    private javax.swing.JButton btnBuscarVenta;
    private javax.swing.JButton btnNuevaVenta;
    private javax.swing.JButton btnVerDetalleVenta;
    private javax.swing.JLabel lblBuscarVenta;
    private javax.swing.JLabel lblSubtituloVentas;
    private javax.swing.JLabel lblTituloVentas;
    private javax.swing.JPanel pnlContenidoVentas;
    private javax.swing.JTable tblVentas;
    private javax.swing.JTextField txtBuscarVenta;
    // End of variables declaration//GEN-END:variables
}
