/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.gamezone.ui;

/**
 *
 * @author USUARIO
 */
public class SaleDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SaleDialog.class.getName());

    /**
     * Creates new form SaleDialog
     */
    public SaleDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblHeaderTitle = new javax.swing.JLabel();
        lblHeaderSubtitle = new javax.swing.JLabel();
        lblCustomer = new javax.swing.JLabel();
        cmbCustomer = new javax.swing.JComboBox<>();
        lblSeller = new javax.swing.JLabel();
        cmbSeller = new javax.swing.JComboBox<>();
        lblSelectProduct = new javax.swing.JLabel();
        cmbProduct = new javax.swing.JComboBox<>();
        chkExtendedWarranty = new javax.swing.JCheckBox();
        btnAddProduct = new javax.swing.JButton();
        spSaleItems = new javax.swing.JScrollPane();
        tblSaleItems = new javax.swing.JTable();
        btnRemoveItem = new javax.swing.JButton();
        lblSubtotalText = new javax.swing.JLabel();
        lblSubtotalValue = new javax.swing.JLabel();
        lblDiscountText = new javax.swing.JLabel();
        lblDiscountValue = new javax.swing.JLabel();
        lblTotalText = new javax.swing.JLabel();
        lblTotalValue = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnConfirmSale = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GameZone - Registrar Nueva Venta");
        setBackground(new java.awt.Color(255, 255, 255));
        setModal(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(20, 40, 75));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeaderTitle.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblHeaderTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblHeaderTitle.setText("Registrar Nueva Venta");
        jPanel1.add(lblHeaderTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 15, 300, 25));

        lblHeaderSubtitle.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblHeaderSubtitle.setForeground(new java.awt.Color(210, 220, 235));
        lblHeaderSubtitle.setText("Punto de venta y facturación de GameZone");
        jPanel1.add(lblHeaderSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 320, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 75));

        lblCustomer.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblCustomer.setForeground(new java.awt.Color(31, 41, 55));
        lblCustomer.setText("Cliente:*");
        getContentPane().add(lblCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 150, 20));

        cmbCustomer.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        cmbCustomer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar cliente..." }));
        getContentPane().add(cmbCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 115, 310, 35));

        lblSeller.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblSeller.setForeground(new java.awt.Color(31, 41, 55));
        lblSeller.setText("Vendedor que atiende:*");
        getContentPane().add(lblSeller, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 180, 20));

        cmbSeller.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        cmbSeller.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar vendedor..." }));
        getContentPane().add(cmbSeller, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 115, 310, 35));

        lblSelectProduct.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblSelectProduct.setText("Agregar producto a la venta:*");
        getContentPane().add(lblSelectProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 165, 250, 20));

        cmbProduct.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        cmbProduct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar producto del catálogo..." }));
        getContentPane().add(cmbProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 370, 35));

        chkExtendedWarranty.setBackground(new java.awt.Color(255, 255, 255));
        chkExtendedWarranty.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        chkExtendedWarranty.setForeground(new java.awt.Color(31, 41, 55));
        chkExtendedWarranty.setText("Garantía Ext. (+10%)");
        getContentPane().add(chkExtendedWarranty, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 195, 150, 25));

        btnAddProduct.setBackground(new java.awt.Color(30, 136, 229));
        btnAddProduct.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnAddProduct.setForeground(new java.awt.Color(255, 255, 255));
        btnAddProduct.setText("+ Agregar");
        btnAddProduct.setBorderPainted(false);
        btnAddProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddProduct.setFocusPainted(false);
        getContentPane().add(btnAddProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 100, 35));

        tblSaleItems.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        tblSaleItems.setForeground(new java.awt.Color(31, 41, 55));
        tblSaleItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Producto", "Precio ($)", "Garantía"
            }
        ));
        spSaleItems.setViewportView(tblSaleItems);

        getContentPane().add(spSaleItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 640, 190));

        btnRemoveItem.setBackground(new java.awt.Color(240, 242, 245));
        btnRemoveItem.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnRemoveItem.setForeground(new java.awt.Color(229, 57, 53));
        btnRemoveItem.setText("Quitar seleccionado");
        btnRemoveItem.setBorderPainted(false);
        btnRemoveItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRemoveItem.setFocusPainted(false);
        getContentPane().add(btnRemoveItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 435, 160, 28));

        lblSubtotalText.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSubtotalText.setForeground(new java.awt.Color(107, 114, 128));
        lblSubtotalText.setText("Subtotal:");
        getContentPane().add(lblSubtotalText, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 475, 100, 20));

        lblSubtotalValue.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblSubtotalValue.setForeground(new java.awt.Color(31, 41, 55));
        lblSubtotalValue.setText("$0.00");
        getContentPane().add(lblSubtotalValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 475, 140, 20));

        lblDiscountText.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDiscountText.setForeground(new java.awt.Color(107, 114, 128));
        lblDiscountText.setText("Descuento:");
        getContentPane().add(lblDiscountText, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, 100, 20));

        lblDiscountValue.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblDiscountValue.setForeground(new java.awt.Color(229, 57, 53));
        lblDiscountValue.setText("-$0.00");
        getContentPane().add(lblDiscountValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 500, 140, 20));

        lblTotalText.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTotalText.setForeground(new java.awt.Color(31, 41, 55));
        lblTotalText.setText("TOTAL:");
        getContentPane().add(lblTotalText, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, 100, 25));

        lblTotalValue.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblTotalValue.setForeground(new java.awt.Color(46, 125, 50));
        lblTotalValue.setText("$0.00");
        getContentPane().add(lblTotalValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 530, 140, 25));

        btnCancel.setBackground(new java.awt.Color(229, 57, 53));
        btnCancel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancelar");
        btnCancel.setBorderPainted(false);
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.setFocusPainted(false);
        btnCancel.addActionListener(this::btnCancelActionPerformed);
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 580, 140, 42));

        btnConfirmSale.setBackground(new java.awt.Color(46, 125, 50));
        btnConfirmSale.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnConfirmSale.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmSale.setText("Confirmar Venta");
        btnConfirmSale.setBorderPainted(false);
        btnConfirmSale.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmSale.setFocusPainted(false);
        getContentPane().add(btnConfirmSale, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 580, 160, 42));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                SaleDialog dialog = new SaleDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirmSale;
    private javax.swing.JButton btnRemoveItem;
    private javax.swing.JCheckBox chkExtendedWarranty;
    private javax.swing.JComboBox<String> cmbCustomer;
    private javax.swing.JComboBox<String> cmbProduct;
    private javax.swing.JComboBox<String> cmbSeller;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCustomer;
    private javax.swing.JLabel lblDiscountText;
    private javax.swing.JLabel lblDiscountValue;
    private javax.swing.JLabel lblHeaderSubtitle;
    private javax.swing.JLabel lblHeaderTitle;
    private javax.swing.JLabel lblSelectProduct;
    private javax.swing.JLabel lblSeller;
    private javax.swing.JLabel lblSubtotalText;
    private javax.swing.JLabel lblSubtotalValue;
    private javax.swing.JLabel lblTotalText;
    private javax.swing.JLabel lblTotalValue;
    private javax.swing.JScrollPane spSaleItems;
    private javax.swing.JTable tblSaleItems;
    // End of variables declaration//GEN-END:variables
}
