/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.gamezone.ui;

import com.gamezone.model.Seller;
import com.gamezone.service.PersonService;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class SellerPanel extends javax.swing.JPanel {

    private PersonService personService;
    /**
     * Creates new form SellerPanel
     */
    public SellerPanel () {
        initComponents();
    }

    public SellerPanel(PersonService personService) {
        this.personService = personService;
        initComponents();
        loadSellers(); // Llena la tabla apenas se abre
    }
    
    public void loadSellers() {
        if (personService == null) {
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblVendedores.
                getModel();
        model.setRowCount(0); // Limpia filas viejas

        for (Seller s : personService.listAllSellers()) {
            model.addRow(new Object[]{
                s.getId(),
                s.getFirstName(),
                s.getLastName(),
                s.getPhone(),
                s.getEmployeecode(),
                s.getShift()
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloVendedores = new javax.swing.JLabel();
        lblSubtituloVendedores = new javax.swing.JLabel();
        pnlContenidoVendedores = new javax.swing.JPanel();
        lblBuscarVendedor = new javax.swing.JLabel();
        txtBuscarVendedor = new javax.swing.JTextField();
        btnBuscarVendedor = new javax.swing.JButton();
        JsVendedores = new javax.swing.JScrollPane();
        tblVendedores = new javax.swing.JTable();

        setBackground(new java.awt.Color(245, 247, 250));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloVendedores.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        lblTituloVendedores.setForeground(new java.awt.Color(31, 41, 55));
        lblTituloVendedores.setText("Vendedores");
        add(lblTituloVendedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 35, 200, 35));

        lblSubtituloVendedores.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSubtituloVendedores.setForeground(new java.awt.Color(107, 114, 128));
        lblSubtituloVendedores.setText("Equipo de ventas y atención al cliente de GameZone.");
        add(lblSubtituloVendedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 75, 400, 25));

        pnlContenidoVendedores.setBackground(new java.awt.Color(255, 255, 255));
        pnlContenidoVendedores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBuscarVendedor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblBuscarVendedor.setForeground(new java.awt.Color(31, 41, 55));
        lblBuscarVendedor.setText("Buscar vendedor");
        pnlContenidoVendedores.add(lblBuscarVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 25, 140, 25));

        txtBuscarVendedor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtBuscarVendedor.addActionListener(this::txtBuscarVendedorActionPerformed);
        pnlContenidoVendedores.add(txtBuscarVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 20, 300, 35));

        btnBuscarVendedor.setBackground(new java.awt.Color(30, 136, 229));
        btnBuscarVendedor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnBuscarVendedor.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarVendedor.setText("Buscar");
        btnBuscarVendedor.setBorderPainted(false);
        btnBuscarVendedor.setFocusPainted(false);
        btnBuscarVendedor.addActionListener(this::btnBuscarVendedorActionPerformed);
        pnlContenidoVendedores.add(btnBuscarVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 110, 35));

        tblVendedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido", "Telefono", "Codigo Empleado", "Turno"
            }
        ));
        JsVendedores.setViewportView(tblVendedores);

        pnlContenidoVendedores.add(JsVendedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 85, 870, 400));

        add(pnlContenidoVendedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 920, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVendedorActionPerformed
        if (personService == null) {
            return;
        }

        String query = txtBuscarVendedor.getText().trim().toLowerCase();

        // Si la caja está vacía, recarga la lista completa:
        if (query.isEmpty()) {
            loadSellers();
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblVendedores.
                getModel();
        model.setRowCount(0); // Limpia la tabla para mostrar solo los que coinciden

        // Filtra por ID, Nombre, Apellido o Código de empleado:
        for (Seller s : personService.listAllSellers()) {
            if (s.getId().toLowerCase().contains(query)
                    || s.getFirstName().toLowerCase().contains(query)
                    || s.getLastName().toLowerCase().contains(query)
                    || s.getEmployeecode().toLowerCase().contains(query)) {

                model.addRow(new Object[]{
                    s.getId(),
                    s.getFirstName(),
                    s.getLastName(),
                    s.getPhone(),
                    s.getEmployeecode(),
                    s.getShift()
                });
            }
        }
    }//GEN-LAST:event_btnBuscarVendedorActionPerformed

    private void txtBuscarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarVendedorActionPerformed
        btnBuscarVendedorActionPerformed(evt);
    }//GEN-LAST:event_txtBuscarVendedorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JsVendedores;
    private javax.swing.JButton btnBuscarVendedor;
    private javax.swing.JLabel lblBuscarVendedor;
    private javax.swing.JLabel lblSubtituloVendedores;
    private javax.swing.JLabel lblTituloVendedores;
    private javax.swing.JPanel pnlContenidoVendedores;
    private javax.swing.JTable tblVendedores;
    private javax.swing.JTextField txtBuscarVendedor;
    // End of variables declaration//GEN-END:variables
}
