/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.gamezone.ui;

/**
 *
 * @author USUARIO
 */
public class SellerPanel extends javax.swing.JPanel {

    /**
     * Creates new form SellerPanel
     */
    public SellerPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloVendedores = new javax.swing.JLabel();
        lblSubtituloVendedores = new javax.swing.JLabel();
        pnlContenidoVendedores = new javax.swing.JPanel();
        lblBuscarVendedor = new javax.swing.JLabel();
        txtBuscarVendedor = new javax.swing.JTextField();
        btnBuscarVendedor = new javax.swing.JButton();
        JsVendedores = new javax.swing.JScrollPane();
        tblVendedores = new javax.swing.JTable();

        setBackground(new java.awt.Color(245, 247, 250));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloVendedores.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        lblTituloVendedores.setForeground(new java.awt.Color(31, 41, 55));
        lblTituloVendedores.setText("Vendedores");
        add(lblTituloVendedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 35, 200, 35));

        lblSubtituloVendedores.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSubtituloVendedores.setForeground(new java.awt.Color(107, 114, 128));
        lblSubtituloVendedores.setText("Equipo de ventas y atención al cliente de GameZone.");
        add(lblSubtituloVendedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 75, 400, 25));

        pnlContenidoVendedores.setBackground(new java.awt.Color(255, 255, 255));
        pnlContenidoVendedores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBuscarVendedor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblBuscarVendedor.setForeground(new java.awt.Color(31, 41, 55));
        lblBuscarVendedor.setText("Buscar vendedor");
        pnlContenidoVendedores.add(lblBuscarVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 25, 140, 25));

        txtBuscarVendedor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        pnlContenidoVendedores.add(txtBuscarVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 20, 300, 35));

        btnBuscarVendedor.setBackground(new java.awt.Color(30, 136, 229));
        btnBuscarVendedor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnBuscarVendedor.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarVendedor.setText("Buscar");
        btnBuscarVendedor.setBorderPainted(false);
        btnBuscarVendedor.setFocusPainted(false);
        pnlContenidoVendedores.add(btnBuscarVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 110, 35));

        tblVendedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido", "Telefono", "Codigo Empleado", "Turno"
            }
        ));
        JsVendedores.setViewportView(tblVendedores);

        pnlContenidoVendedores.add(JsVendedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 85, 870, 400));

        add(pnlContenidoVendedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 920, 520));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JsVendedores;
    private javax.swing.JButton btnBuscarVendedor;
    private javax.swing.JLabel lblBuscarVendedor;
    private javax.swing.JLabel lblSubtituloVendedores;
    private javax.swing.JLabel lblTituloVendedores;
    private javax.swing.JPanel pnlContenidoVendedores;
    private javax.swing.JTable tblVendedores;
    private javax.swing.JTextField txtBuscarVendedor;
    // End of variables declaration//GEN-END:variables
}
